### ISSUE TITLE
[ios] Can't access menu and settings in portrait modus

### ISSUE THREAD

**Issue by getwet** [floccusaddon/floccus#1202]
Hi,

many thanks to bring the app to ios. But the nodge, clock and network status icons on my iphone overlapp the app menu and setting, so can't only access in landscape mode. Iphone 12 with ios 15.5.

Screenshot:
https://ibb.co/XS4gnyQ

Wishlist:
- Add Bookmarks with share menu.
- Connect to Nextcloud Bookmarks with App Password

best
Ralf

**Comment by marcelklehr** [comment]
Shoudl be fixed with the latest update :)

**Comment by marcelklehr** [comment]
> 
>    Add Bookmarks with share menu.
>    Connect to Nextcloud Bookmarks with App Password
>

Both are planned :)

**Comment by getwet** [comment]
Now I've got a white bar if on nogde or not. The view in options are not fixed.
Screenshot: https://ibb.co/JjLQHy3

**Comment by marcelklehr** [comment]
How is it looking with v4.16.0?

**Comment by getwet** [comment]
It's accessible. Thanks

**Comment by marcelklehr** [comment]
The white background around the notch could probably be made to match the dark theme.

**Comment by getwet** [comment]
That would be good to have a better look. But not a problem. Thanks
