### ISSUE TITLE
pull up/pull down don't work anymore on gdrive

### ISSUE THREAD

**Issue by 424344** [floccusaddon/floccus#1363]
### Which version of floccus are you using?

4.19.0

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

edge  111.0.1661.54, chrome 111.0.5563.111, firefox 111.0.1

### Describe the Bug

since version 4.19.0 the pull down/pull up functions doesn't work anymore.
note that previous version was working (but bookmarks order was wrong).

I did a pull up from chrome, and a pull down on edge and firefox.

the result is that the current bookmarks on edge and firefox are deleted.
and the bookmarks from chrome are not added.

### Expected Behavior

get same bookmarks as source browser (chrome)

### To Reproduce

do a pull up from chrome, and a pull down to edge/firefox.

I've attached a log of the pull up (chrome) and pull down (edge).

[floccus-4.19.0-2023-03-27-pull-up-redacted.log](https://github.com/floccusaddon/floccus/files/11076378/floccus-4.19.0-2023-03-27-pull-up-redacted.log)

[floccus-4.19.0-2023-03-27-pull-down-redacted.log](https://github.com/floccusaddon/floccus/files/11076380/floccus-4.19.0-2023-03-27-pull-down-redacted.log)

### Debug log provided

- [X] I have provided a debug log file

**Comment by eihnat** [comment]
I seem to have same issue with nextcloud. reinstalled pc, won't sync/pull down bookmarks. 
sync works when i manually imported bookmarks and did minor change (added 1 bookmark). 
tried on firefox and brave browser.

log from brave browser.
[floccus-4.19.0-2023-03-27.log](https://github.com/floccusaddon/floccus/files/11078509/floccus-4.19.0-2023-03-27.log)

**Comment by AlphaHasi** [comment]
Same here with Google Drive, I reconized that the marks on my two devices are not in sync anymore, push and pull did not help, so I deleted the files from Google, deleted cache and cookies (just in case) and pushed again. It tells me everything is fine, but there isn't even a file on Google. Log ends with:
`2023-03-28T12:10:25.882Z onSyncComplete
2023-03-28T12:10:26.116Z No changes to the server version necessary
2023-03-28T12:10:26.674Z Successfully ended sync process for account Google Drive: bookmarks.xbel`

**Comment by marcelklehr** [comment]
Should be fixed with v4.19.1 -- coming to a machine near you soon-ish.

**Comment by AlphaHasi** [comment]
Sorry, still doesn't work with Floccus version 4.19.1. in Firefox (did not test Chromebook yet).

Infos like described above:
- Floccus version 4.19.1.
- Sync method: Google Drive (old file deleted, logged out and in again, space available)
- Firefox 111.0.1 (64-Bit), Windows 10
- bug: sync starts (icon with the arrows circles), synch ends, message "everthing is fine" (in German "Alles gut") is displayed, but file on Google drive is not updated (if present) and is not created when missing. So far I tried sync an existing file, push once with existing file, push without existing file, even deleted Floccus account and set up new account and delted Floccus cache
- log: [floccus-4.19.1-2023-03-30.log](https://github.com/floccusaddon/floccus/files/11116330/floccus-4.19.1-2023-03-30.log)

Not sure what I should try next.

Cheers,
Torsten

**Comment by marcelklehr** [comment]
You probably moved the file on google drive into the trash? Floccus will still successfully sync to the file wherever you move it, even if you move it into the trash.

**Comment by AlphaHasi** [comment]
@marcelklehr After I deleted the file from the trash and did a new setup it now works again, thanks a lot!
