### ISSUE TITLE
Bookmarks can't be synchronized and show "Scheduled"

### ISSUE THREAD

**Issue by Ganya-A** [floccusaddon/floccus#1548]
### Which version of floccus are you using?

5.0.8 5.0.9

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Edge 

### What kind of WebDAV server are you using? (if relevant)

jianguoyun

### Describe the Bug

I can't get both of my computers to sync. 
Scheduled：This profile will be synced soon. We're either waiting for other devices of yours, or other profiles on this device, to finish syncing.

### Expected Behavior

-

### To Reproduce

-

### Debug log provided

- [X] I have provided a debug log file

**Comment by Syzygy33** [comment]
> ### Which version of floccus are you using?
> 5.0.8 5.0.9
> 
> ### Sync method
> WebDAV
> 
> ### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.
> Edge
> 
> ### Which version of Nextcloud Bookmarks are you using? (if relevant)
> _No response_
> 
> ### Which version of Nextcloud? (if relevant)
> _No response_
> 
> ### What kind of WebDAV server are you using? (if relevant)
> jianguoyun
> 
> ### Describe the Bug
> I can't get both of my computers to sync. Scheduled：This profile will be synced soon. We're either waiting for other devices of yours, or other profiles on this device, to finish syncing.
> 
> ### Expected Behavior
> 
> ### To Reproduce
> 
> ### Debug log provided
> * [x]  I have provided a debug log file

try to delete the .lock file

**Comment by Ganya-A** [comment]
> > ### Which version of floccus are you using?
> > 5.0.8 5.0.9
> > ### Sync method
> > WebDAV
> > ### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.
> > Edge
> > ### Which version of Nextcloud Bookmarks are you using? (if relevant)
> > _No response_
> > ### Which version of Nextcloud? (if relevant)
> > _No response_
> > ### What kind of WebDAV server are you using? (if relevant)
> > jianguoyun
> > ### Describe the Bug
> > I can't get both of my computers to sync. Scheduled：This profile will be synced soon. We're either waiting for other devices of yours, or other profiles on this device, to finish syncing.
> > ### Expected Behavior
> > ### To Reproduce
> > ### Debug log provided
> > 
> > * [x]   I have provided a debug log file
> 
> try to delete the .lock file

After deleting the. lock file, it will appear soon.

**Comment by Syzygy33** [comment]
or use Google drive？

---- Replied Message ----
| From | ***@***.***> |
| Date | 03/01/2024 07:31 |
| To | floccusaddon/floccus ***@***.***> |
| Cc | Syzygy33 ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [floccusaddon/floccus] Bookmarks can't be synchronized and show“Scheduled” (Issue #1548) |

Which version of floccus are you using?

5.0.8 5.0.9

Sync method

WebDAV

Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Edge

Which version of Nextcloud Bookmarks are you using? (if relevant)

No response

Which version of Nextcloud? (if relevant)

No response

What kind of WebDAV server are you using? (if relevant)

jianguoyun

Describe the Bug

I can't get both of my computers to sync. Scheduled：This profile will be synced soon. We're either waiting for other devices of yours, or other profiles on this device, to finish syncing.

Expected Behavior
To Reproduce
Debug log provided
I have provided a debug log file

try to delete the .lock file

After deleting the. lock file, it will appear soon.

**Comment by marcelklehr** [comment]
Please make sure

* that all your Floccus instances on Chrome (or variants thereof, like Edge, Brave, Vivaldi etc.) are on v5.0.9
* that all your Floccus instances on Firefox are on v5.0.8

Judging from the chrome webstore statistics there are still around 800 Chrome instances on v5.0.6, which has this bug.

**Comment by Ganya-A** [comment]
> 请确保
> 
> * 您在 Chrome 上的所有 Floccus 实例（或其变体，如 Edge、Brave、Vivaldi 等）都在 v5.0.9 上
> * Firefox 上的所有 Floccus 实例都在 v5.0.8 上
> 
> 从 chrome 网店统计来看，v5.0.6 上还有大约 800 个 Chrome 实例，存在此 bug。

I've updated all device versions to 5.0.9, two EDGE, and one mobile browser, and I'm still having this problem.

**Comment by marcelklehr** [comment]
So, this should only really be a problem when syncing via WebDAV like @Ganya-A and @idzyr 

@InfamousUser is syncing via Nextcloud Bookmarks, which should automatically timeout its lock. Is this still happening for you?

@traviss64 are you syncing via Nextcloud Bookmarks or via Nextcloud files (ie. webdav)?

**Comment by idzyr** [comment]
@marcelklehr 
I have the same issue as the original post, but I'm using a PC with Chrome(v122.0.6261.112). I tried deleting the lock file, but after a while, it stops working again.

**Comment by marcelklehr** [comment]
This should be resolved with v5.0.10, please let me know if it works :)

**Comment by InfamousUser** [comment]
Updated to v5.0.10 on Chrome, no change.

**Comment by beyercj** [comment]
Updated to v5.0.10 on Firefox 115.8.0esr for Linux and to v5.0.11 on Android 11 on Samsung Galaxy A12, no change either on webdav.smartdrive.web.de (webspace almost full). However, synchronisation worked fine on webdav.vodafonemail.de (webspace almost empty), so might not have anything to do with floccus.

**Comment by marcelklehr** [comment]
So, this issue usually stems from a leftover lock file that prevents all clients from syncing. v5.0.10 should mitigate that by forcing floccus to sync anyway, if it has waited long enough. If this does not fix this for you all, then we might have a more serious issue of an interrupted sync process. This would be the case if for example if floccus does sometimes start to sync but then stops, likely after about 5mins, only to then show the "scheduled Sync" message one minute later, which again stems from the leftover lock file. On firefox I think you can also verify if this is the problem by opening the browser debug log. The browser will then no longer interrupt the sync process and thus floccus should sync correctly after some time waiting for the lock to expire and go back to an "All good" green status, **while the debug window is open**.

Here's how to open the debug window:

#### Firefox
* Go to `about:debugging`
* Go to `This firefox`
* click on `debug` button next to floccus entry to open the console

Not sure, if this will work in chrome, but you may try:

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: " to open the console

**Comment by InfamousUser** [comment]
I am receiving "QUEUING POST", "FETCHING POST", "Receiving response for POST" and then "Resource is locked, trying again soon" in the Floccus logs. I should note that it did sync the folders to the server, but none of the actual bookmarks are populated.

**Comment by lychnikon** [comment]
I am also having this same issue, lock on Chrome plugin preventing sync to Nextcloud, updates current. Stuck on "Resource is locked, trying again soon" in logs.

**Comment by marcelklehr** [comment]
@InfamousUser You will need to wait until the lock is cleared for the above thing with the debug window to work. Only unpopulated folders is a bad sign, though...

**Comment by InfamousUser** [comment]
How long do I need to wait? Sever has been off for the past few days, I just turned it on and still the same problem. Is there a way to force this or what am I supposed to do?

**Comment by marcelklehr** [comment]
Doesn't matter anymore, I've been able to reproduce this now and can debug from there. It looks like Chrome blatantly shuts down extension service workers after running some amount of minutes. There's not gonna be an easy fix for this, I think. Should still be doable though

**Comment by smth** [comment]
I also have this problem. Two Firefox browsers using v5.0.10 (though one was recently on 5.0.5). My server does have a lock file on it.

**Comment by cng10001** [comment]
> I also have this problem. Two Firefox browsers using v5.0.10 (though one was recently on 5.0.5). My server does have a lock file on it.

Add a new account and use other ways of sync for now.Hope the author solve the problem soon.

**Comment by truthsword** [comment]
Updated Firefox from 5.0.8 to 5.0.10 and within a short time the lock file imposed itself. Is rollback possible? I deleted the lock file, but can't do that regularly. I'm using WebDAV.

**Comment by cng10001** [comment]
> Updated Firefox from 5.0.8 to 5.0.10 and within a short time the lock file imposed itself. Is rollback possible? I deleted the lock file, but can't do that regularly. I'm using WebDAV.

I delete the lock file ,then remove my account and re-add it. You can try this too, no loss anyway

**Comment by marcelklehr** [comment]
I'm working on the fix for this. It's quite involved, but I should be able to provide a beta soon, for you to test :rocket:

**Comment by InfamousUser** [comment]
Great to hear it is getting fixed! Thanks for the update!

**Comment by marcelklehr** [comment]
Hello everyone, there's now a beta release available which should fix this issue: https://github.com/floccusaddon/floccus/releases/tag/v5.0.12-beta.1

## Firefox
On firefox you should be able to install this by

* Unzipping the firefox build somewhere
* Going to `about:debugging` and selecting the unzipped folder

## Chrome
On chrome you should be able to install this by

* Unzipping the chrome build somewhere
* Going to `chrome://extensions`
* Enabling developer mode
* Loading the manifest.json from the unzipped folder

## Android
On android you should be able to install this by

* Opening the apk or aab build, if you previously installed floccus from Google Play or Github
* (If you installed from f-droid, you'll need to uninstall unfortunately, because f-droid has its own set of keys)

**Comment by cng10001** [comment]
> Hello everyone, there's now a beta release available which should fix this issue: https://github.com/floccusaddon/floccus/releases/tag/v5.0.12-beta.1
> 
> ## Firefox
> On firefox you should be able to install this by
> 
> * Unzipping the firefox build somewhere
> * Going to `about:debugging` -> "This Firefox" -> Load temporary extension -> and selecting the unzipped folder
> 
> ## Chrome
> On chrome you should be able to install this by
> 
> * Unzipping the chrome build somewhere
> * Going to `chrome://extensions`
> * Enabling developer mode
> * Click "Load unpacked" -> select the manifest.json from the unzipped folder
> 
> ## Android
> On android you should be able to install this by
> 
> * Opening the apk or aab build, if you previously installed floccus from Google Play or Github
> * (If you installed from f-droid, you'll need to uninstall unfortunately, because f-droid has its own set of keys)
> 
> ## Important
> * Please make a backup of your bookmarks before trying this out!
> 
> Let me know how it goes ✌️

It seems the problem still exits
![emm](https://github.com/floccusaddon/floccus/assets/115156545/1e19d962-cf93-48e1-9941-72c12f612986)

**Comment by marcelklehr** [comment]
@cng10001 You will still need to wait or remove the lock manually, initially, as described above. Afterwards it shouldn't get stuck like this anymore.

**Comment by marcelklehr** [comment]
Any other testers? Would be great if a few of you could test this, otherwise I have to release it untested :S

**Comment by InfamousUser** [comment]
Well, unlike the previous version, this one did manage to sync something. It synced around 150 bookmarks before going to the "Scheduled" stage and stopping there. Errors in the log are identical to the post https://github.com/floccusaddon/floccus/issues/1548#issuecomment-1992606654 or being E017 network error which changes to the "This profile will be synced soon..." one upon depressing the sync now button.

**Comment by marcelklehr** [comment]
@InfamousUser Thank you for taking it for a spin! Are there any other floccus instances running that haven't been updated to the beta version, yet?

**Comment by InfamousUser** [comment]
> @InfamousUser Thank you for taking it for a spin! Are there any other floccus instances running that haven't been updated to the beta version, yet?

There is the original Floccus, the beta doesnt update it but make an additional extension unfortunately. It had its autosync disabled though and hasn't synced as far as I'm aware and the last error in its log is 17.03.2024. I can delete it if you think it's interfering in some way?

**Comment by marcelklehr** [comment]
Mh, probably best to disable the original extension instance, yeah

**Comment by InfamousUser** [comment]
It seems to be randomly syncing more bookmarks but this is not what I would call a working fix. It has synced another 100 or so bookmarks. When you press the sync it latches but then it keeps switching between syncing and scheduled. Bu then after a while it "finishes" and you have to trigger it again because it has not synced the bookmarks.

**Comment by cng10001** [comment]
> @cng10001 You will still need to wait or remove the lock manually, initially, as described above. Afterwards it shouldn't get stuck like this anymore.

Maybe my problem is I was still using a lower version of chrome,
I updated the browser and I'll watch it for more days

**Comment by peterschmidler** [comment]
Also facing that issue, even after updating on Chrome, Firefox and iOS not using WebDAV. Is there a way to manually remove the lock file? Or how long will I have to wait until the lockfile gets deleted automatically?

**Comment by marcelklehr** [comment]
Can you confirm whether it syncs for roughly 5 minutes, at least, before it switches back to "scheduled"?

**Comment by marcelklehr** [comment]
Chrome version may be interesting as well, indeed

**Comment by InfamousUser** [comment]
I do not and cannot have Chrome v110+ due to Google blocking updates on older Windows so count me out for testing that...

**Comment by marcelklehr** [comment]
Oh Wow! So you do have pre v110 Chrome, so the fix I built may work after all. Sorry about the Chrome updates!

**Comment by InfamousUser** [comment]
Geez, never thought that'd be the issue! I can try it on a different PC, with newer browser, but I have a feeling that will work since it doesn't really help! Will get back to you with the results!

**Comment by marcelklehr** [comment]
It's not the root cause, but part of my fix only works post v110

**Comment by marcelklehr** [comment]
Alright, since it works for me I'll roll this out stage-wise in production now to get people to test it.

**Comment by marcelklehr** [comment]
Staged roll-out failed for some reason, so now this is on prod 100% :see_no_evil: 
Anyway.  @Ganya-A and @idzyr and @beyercj Are you on v5.0.12 already? Does it work now after removing the lock file manually once?

**Comment by InfamousUser** [comment]
Just to confirm the fix works for me, but everyone already knows I guess.

**Comment by marcelklehr** [comment]
Thank you @InfamousUser always good to get confirmation :)

**Comment by ivanjx** [comment]
where is the .lock file on nextcloud?

**Comment by marcelklehr** [comment]
@ivanjx please open a new discussion or a new issue

**Comment by joshqou** [comment]
This can still happen on version `5.2.7` if you start and immediately cancel a sync. i.e: accidentially double-click the sync now button. There should really be a button to manually remove the lock file so users don't have to open devtools just to get their bookmarks syncing again

**Comment by marcelklehr** [comment]
@joshqou Good idea! Can you open a feature request for this?

**Comment by joshqou** [comment]
@marcelklehr Created at #1769
