### ISSUE TITLE
"Failed to fetch" and blank settings screen in android app using git

### ISSUE THREAD

**Issue by mortifactor** [floccusaddon/floccus#1608]
### Which version of floccus are you using?

5.1.1

### How many bookmarks do you have, roughly?

1000+

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Git

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android 9 Honor 20

### Describe the Bug

I'm importing profile from browser, which works. But I tried creating same profile from scratch and it did not work either.
Profile uses github private repository.
So I have "Failed to fetch" error after sync. And if I go to settings I get blank screen. That is why I can't attach debug logs.
You can see it on video below.

### Expected Behavior

Well, it should sync I believe.

### To Reproduce

https://github.com/floccusaddon/floccus/assets/1426349/74cceade-5eb8-4992-b9e2-f8f3ffe6322c

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
It's possible this is a network problem. I'll look into the settings issue.

**Comment by babblerz** [comment]
I have the same issue. Using 5.1.2. This is what I get in the android log:

Capacitor/Console: File: http://localhost/#/tree/17158905901720.4856727622664514 - Line 0 - Msg: Access to fetch at 'https://redacted.com/redactedusername/floccusbookmarks/info/refs?service=git-upload-pack' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

The same server with the browser plugin works ok.
Also tried it with a github.com account and the error is the same.

**Comment by marcelklehr** [comment]
Ah, thank you for the extended log, @babblerz The error makes sense now. I'll look into fixing this.

**Comment by marcelklehr** [comment]
Fixed the settings issue. I can reproduce the CORS issue, I'll look into fixing it.

**Comment by marcelklehr** [comment]
Upstream blocker: https://github.com/ionic-team/capacitor/issues/7473

**Comment by dcanl** [comment]
Hello,

Just posting to follow this issue which I encounter myself too.

Thank you for your work!

**Comment by mdcayton** [comment]
Similar issue. Looks like if fails to checkout the branch. 

> 2024-05-31T16:44:21.293Z Starting sync process for account user@mail.tld@git.webiste.tld:bookmarks.xbel
2024-05-31T16:44:21.300Z onSyncStart: begin
2024-05-31T16:44:21.302Z (git) init
2024-05-31T16:44:21.392Z (git) fetch from remote
2024-05-31T16:44:21.810Z (git) checkout branch main
2024-05-31T16:44:21.826Z onSyncFail
2024-05-31T16:44:21.830Z Syncing failed with Failed to checkout "main" because commit ##### is not available locally. Do a git fetch to make the branch available locally.
2024-05-31T16:44:21.840Z onSyncFail

**Comment by faan11** [comment]
Hi @marcelklehr 
any updates about this issue? Today I have installed the application and i faced this issue with the same error log.

**Comment by marcelklehr** [comment]
@faan11 Sadly not, it's an upstream issue in capacitor: https://github.com/ionic-team/capacitor/issues/7473

**Comment by marcelklehr** [comment]
Yes, now we need to wait for a release from them, then this issue can be fixed :)

**Comment by Crunchbits** [comment]
Looks like a release was just made from them with the fix

**Comment by faan11** [comment]
Yeah the issue has been fixed in v5.7.7 and v6.1.1

**Comment by marcelklehr** [comment]
Mmmh, now with the latest capacitor version it just hangs on git fetch :thinking:

**Comment by ChandraSaiKarthik** [comment]
I had a similar issue with gitea on my OnePlus Mobile running Android 14.1 but syncs smoothly on my laptop.
Let me know what other details you might need for troubleshooting.

**Comment by elvisisvan** [comment]
> I had a similar issue (hangs with sync and hangs complete mobile) with gitea on my OnePlus Mobile running Android 14.1 but syncs smoothly on my laptop. Let me know what other details you might need for troubleshooting.

so floccus mobile git sync is not working for your phone too? my samsung phone running android 12 floccus v5.3.1 is having the same issue, the app refreshes countless times and still no bookmark appears

![Screenshot_20241102_132653_floccus bookmark sync](https://github.com/user-attachments/assets/b8d57d68-b024-460f-84f7-54b89d14da3f)

**Comment by unavailable500** [comment]
> > I had a similar issue (hangs with sync and hangs complete mobile) with gitea on my OnePlus Mobile running Android 14.1 but syncs smoothly on my laptop. Let me know what other details you might need for troubleshooting.
> 
> so floccus mobile git sync is not working for your phone too? my samsung phone running android 12 floccus v5.3.1 is having the same issue, the app refreshes countless times and still no bookmark appears
> 
> ![Screenshot_20241102_132653_floccus bookmark sync](https://private-user-images.githubusercontent.com/69122770/382453037-b8d57d68-b024-460f-84f7-54b89d14da3f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NDU1NzksIm5iZiI6MTczMTk0NTI3OSwicGF0aCI6Ii82OTEyMjc3MC8zODI0NTMwMzctYjhkNTdkNjgtYjAyNC00NjBmLTg0ZjctNTRiODlkMTRkYTNmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDE1NTQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhMDMyNTVjMDQwMjgzOGRhNGUzNDQ1NGI3YmZhNDgxZDI1YjQzZDg3ZTM3OTY1MWRjZTY2NmNhYWUwZDAxODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WaK51eDLG4wgkm_pjs61R4bG8PJ561lWc_r0YL6Ew1c)

Same here: floccus 5.3.3 Android 10

**Comment by yashovardhan99** [comment]
Just bumping this thread. I have the same issue on v5.3.4 with Android 14.

**Comment by endlesssecurity** [comment]
Unfortunately +1 v5.3.4 with android 14

**Comment by marcelklehr** [comment]
Please don't comment unless you have substantial contribution for this discussion. Git is known to not work on Android until the capacitor http implementation is fixed, sadly. I'm sorry about this.

**Comment by faan11** [comment]
Hi @marcelklehr, 
i've checked the related issues in the capacitor repo. 
It seems that they have been solved and merged. The one left are about HTTP cookies and this should not concern this bug ( issues 6196 6197 ).
Did you try to test the application with the current latest version (7.0.1)?
Let us know,

**Comment by marcelklehr** [comment]
Hey @faan11 
Thanks for the heads up, I will try updating to 7.x and see how it goes :)

**Comment by marcelklehr** [comment]
Still no dice, unfortunately. I suspect that blobs are still not supported: https://github.com/ionic-team/capacitor/issues/6177

**Comment by faan11** [comment]
This should be the issue https://github.com/ionic-team/capacitor/issues/6126 , the workaround seems to be the solution: https://github.com/ionic-team/capacitor/issues/6126#issuecomment-1468124406 
Maybe this can solve the problem

**Comment by marcelklehr** [comment]
We cannot use Capacitor.request sadly because [it only allows string and JSON as body format](https://capacitorjs.com/docs/apis/http#httpoptions)

**Comment by faan11** [comment]
I'm wondering, Should we add a custom implementation of git using custom code?

https://capacitorjs.com/docs/android/custom-code
https://capacitorjs.com/docs/ios/custom-code

What do you think @marcelklehr ? The issues has been going on for a year.

**Comment by marcelklehr** [comment]
mh, I would like to avoid implementing git myself in both Java and Objective c

**Comment by wes1993** [comment]
There are some news about this issue? I’m on iOS and the same error eccurs…

**Comment by peter-lyons-kehl** [comment]
Limited & work-in-progress workaround: ["Mises" Chromium-based mobile-only browser](https://www.mises.site/), [github.com/mises-id/mises-browser-core](https://github.com/mises-id/mises-browser-core), supports Floccus (and many/any? other) CHROME EXTENSION out of the box on [Android](https://play.google.com/store/apps/details?id=site.mises.browser). The browser exists for [iOS, too](https://apps.apple.com/us/app/mises-browser/id6451129542).

(Disclaimer: I'm not affiliated; It does have bugs and annoyances.)
- Frequent ads (maybe after an initial period?). However, they are collapsible or can be dismissed.
- No Google sync (and of course, no Mozilla sync). There is an option to create a Mises account, but that's for a "wallet" (generic payment and/or a "crypto wallet", no idea).
- No Chrome/standard Chromium-like warnings about extensions that may be shut down soon by/on Chrome/standard Chromium. Of course, to get an extension from Chrome store, the store needs to allow it.
  I did download (an other extension's) .CRX (from crx4chrome), but the browser didn't install it (not even with "Extensions" page > "Developer mode"  turned on).
- The only Android browser that (on common stock, not-rooted devices) doesn't kill background tabs. It doesn't kill even if the whole browser is in the background and the screen is off/locked. (I'm yet to see about the battery.)
- Floccus happily synced in some 1,800 (and other 500) bookmarks from my GitHub repo. (So far I'm using only one way sync-in-and-override.)
- Sometimes the browser crashes.
- The only Android browser that remembers the most recently opened bookmark folder. If you close the bookmark navigation tab (with "X" near the top right), next time you open bookmarks (from the menu), it will open that same folder. Chrome bookmark manager/search extensions seem to work, too.
- Getting back to Floccus (or any? installed extension's) installation settings by clicking the toolbar extensions button (puzzle piece) > then choosing "Floccus" (or any? installed extension) seems to (sometimes?) fail.
  What works more: clicking the toolbar extensions (puzzle piece) button > "Extensions" > then choose "Floccus" (or other ext.).
- New tabs show some (non-configurable?) crypto/related news.
- Try both portrait and landscape (you may like one more).
- FAST, except when showing (and/or downloading?) ads. However, the browser is under Mozilla Pub. license, so it could be forked.

**Comment by wes1993** [comment]
Thanks for help me.
Unfortunately my need is to keep using Safari on iOS…

Best regards
Stefano

**Comment by leonamduarte** [comment]
Any news on this issue?
