### ISSUE TITLE
android version can't fetch newly added bookmark via webdav

### ISSUE THREAD

**Issue by chinagaofeng** [floccusaddon/floccus#1621]
### Which version of floccus are you using?

5.1.3

### How many bookmarks do you have, roughly?

251

### Are you using other means to sync bookmarks in parallel to floccus?

no

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

msedge 125.0.2535.51

### Describe the Bug

strategy in PC msedge floccus ext: 始终上传本地更改并撤销来自其他浏览器的更改
strategy in Android floccus app: 始终撤消本地更改并从其他浏览器下载更改
symptom:
android version can't sync(fetch) the full bookmarks.xbel file, while the file is updated correctly in webdav folder

### Expected Behavior

android version can sync correctly

### To Reproduce

1. add a new item in PC, then sync
2. in webdav folder, view the bookmars.xbel, the new item exists. till now, 50% success
3. then sync in android, nothing happen, the new item can't be fetch, even manually clear cache

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
> android version can't sync(fetch)

What do you actually see when you say it can't sync?

**Comment by chinagaofeng** [comment]
> > android version can't sync(fetch)
> 
> What do you actually see when you say it can't sync?

the sync progress normally, no error, but nothing change in the content: the newly added item witch shown in webdav file can not be sync to phone

**Comment by marcelklehr** [comment]
Can you erify in the bookmarks file in webdav whether the problem is that floccus in edge does not push or that the android app does not pull? Please post a redacted log of that failing sync run here then.

**Comment by slavexe** [comment]
I just installed the android app from fdroid and set it up with webdav. None of my bookmarks sync to the android app even though syncing between firefox browsers on different machines using the extension works perfectly. Interestingly, when I press the sync button in the android app and then attempt to sync shortly after from the firefox extension on a different machine, the firefox extension will warn me that all my bookmarks will get deleted if I continue with the sync. So from what I can tell it seems the android app attempts to completely erase the contents of the file on the webdav server when it tries to sync. This behavior seems to match what happened here #1624.

**Comment by kolinger** [comment]
I have similar issues between Chrome Floccus and Android Floccus. I already have existing data on both sides. If I add something from Android - it works correctly in the Chrome but the opposite is broken - if I add something from Chrome, not only Android doesn't sees it but it overrides WebDAV state with it's own, thus effectively deletes anything what comes from WebDAV/other sources.

This would also explain the reports form others where new/empty Android Floccus deletes everything since it just pushes it's own current state without sync.

**Comment by marcelklehr** [comment]
Can you please try if this is still happening with v5.1.4?

**Comment by kolinger** [comment]
I tried with 5.1.4 and it's intermittent. Most of the time I see case where Chrome does change (doesn't matter if adds, removes, edits), .xbel has the change and Android overrides it with it's own state regardless. It did work correctly couple times but I don't see any pattern between when it does and doesn't.

This log captures when .xbel gets 1 new bookmark and Android decided it should be removed: [floccus-5.1.4-2024-05-27-redacted.log](https://github.com/floccusaddon/floccus/files/15451805/floccus-5.1.4-2024-05-27-redacted.log). It doesn't happen right away - first sync doesn't seem to do anything in the UI but second sync does the remove stuff. So it's seems like Android gets it wrong and thinks his local tree is newer than WebDAV .xbel but that's not the case.

**Comment by marcelklehr** [comment]
I think this may have to do with the tree reloading code I added recently...

**Comment by kolinger** [comment]
I think this started from 5.1.2, 5.1.1 is fine.

**Comment by marcelklehr** [comment]
> I think this started from 5.1.2

Spot on! That's when the tree reloading was introduced. I'm building an alpha version with a possible fix, so you can test.

**Comment by kolinger** [comment]
I tried to revert changes made in 0c6a74d on top of 5.1.4 and it didn't fix it, it's still broken, so I'm puzzled what change is the cause. What I did see between 5.1.1 (and 5.1.2/5.1.4) was the "can't sync because of lock" message and that's not something that 5.1.2 and up did even if I did many rapid synces from both devices.

**Comment by kolinger** [comment]
I see that `treeChanged` condition inside LOAD_TREE is satisfied during sync and that's for sure not correct, this should be satisfied only on resume. I guess sync is successful, it calls LOAD_TREE and the LOAD_TREE sees that sync changed the tree so it restores old tree and this old tree gets synced next time thus it will erase any external changes?

**Comment by marcelklehr** [comment]
[floccus-build-v5.1.5-alpha.1.zip](https://github.com/floccusaddon/floccus/files/15453730/floccus-build-v5.1.5-alpha.1.zip)

**Comment by kolinger** [comment]
I'm not sure if that's just me but the 5.1.5-alpha1 gives me just loading logo as if the app crashed. Deleted data, clean install and still logo.

```
2024-05-27 11:25:48.542 11951-13748 Capacitor               usap64                               D  Handling local request: http://localhost/js/81.js
2024-05-27 11:25:48.542 11951-13748 Capacitor               usap64                               E  Unable to open asset URL: http://localhost/js/81.js
2024-05-27 11:25:48.544 11951-13748 chatty                  usap64                               I  uid=10625(org.handmadeideas.floccus) ThreadPoolForeg identical 2 lines
2024-05-27 11:25:48.544 11951-13748 Capacitor               usap64                               E  Unable to open asset URL: http://localhost/js/81.js
2024-05-27 11:25:48.546 11951-13748 Capacitor               usap64                               D  Handling local request: http://localhost/js/native.js
2024-05-27 11:25:48.557 11951-13748 Capacitor               usap64                               D  Handling local request: http://localhost/favicon.ico
```

Logcat says this. The chunks are broken?

**Comment by marcelklehr** [comment]
Ah, damn. I didn't check the build :see_no_evil: But since you built it yourself we know it works.

**Comment by marcelklehr** [comment]
Ive released https://github.com/floccusaddon/floccus/releases/tag/v5.1.5 which should fix this. Please confirm

**Comment by kolinger** [comment]
5.1.5 didn't fix it, I did clean install and first thing it did was to delete all my stuff, so for sure not correct, basically the same thing as 5.1.2-5.1.4.

**Comment by marcelklehr** [comment]
I think the issue is because the resume handler is inside the Vue component created hook. It might be that this creates a loop

**Comment by kolinger** [comment]
I did remove App.addListener and it didn't change anything.

I see now you didn't revert everything from `src/ui/store/native/actions.js` `async [actions.LOAD_TREE]`, you did leave `await tree.load()` behind. That wasn't originally there it's [new addition](https://github.com/floccusaddon/floccus/commit/0c6a74d0f9c65a562493626773cb99be4df06c62#diff-693fc47db0a3dd4ab7fe773bc1c64be73180fda24e7ff60bd3503866b7f00947). That's mistake I did too when manually reverting the 0c6a74d. But If I take 5.1.5 and remove this addition then it starts to work...

**Comment by marcelklehr** [comment]
Yes, you're right! Thanks for getting to the bottom of this! :blue_heart:

**Comment by marcelklehr** [comment]
So, https://github.com/floccusaddon/floccus/releases/tag/v5.1.7 should finally fix this

**Comment by kolinger** [comment]
Yes it did, I can confirm fresh install of 5.1.7 did first pull from WebDAV successfully. If I make change in browser, the Android floccus sees it, if I make change in Android the browser sees it as well so WebDAV sync now works both ways as expected.
