### ISSUE TITLE
sharing to ios app no longer works

### ISSUE THREAD

**Issue by ivanjx** [floccusaddon/floccus#1758]
### Which version of floccus are you using?

5.3.1

### How many bookmarks do you have, roughly?

100+

### Are you using other means to sync bookmarks in parallel to floccus?

no

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

iphone 13 ios 18.1

### Describe the Bug

i usually add new bookmarks by sharing it from safari to the floccus app but after the last update a few days ago, it no longer works for some reason.

### Expected Behavior

sharing works

### To Reproduce

1. open a site in safari
2. click share button
3. select floccus

https://github.com/user-attachments/assets/b732d6fc-14b0-4b98-b090-042f2f0e69c1

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Confirmed

**Comment by marcelklehr** [comment]
This is due to a build failure that should be fixed in v5.3.2

**Comment by ivanjx** [comment]
i will need to wait for app store update since i dont have a mac

**Comment by ivanjx** [comment]
just updated now and sharing still not working unfortunately

**Comment by marcelklehr** [comment]
Mh, you might need to restart your browser

**Comment by ivanjx** [comment]
still not working. already tried multiple apps to share into floccus and none of them works.

**Comment by ivanjx** [comment]
there seem to be a discrepancy

![IMG_5225](https://github.com/user-attachments/assets/d61eed11-b946-4825-8616-684a7c99d2bf)
![IMG_5226](https://github.com/user-attachments/assets/24ee6265-b5dd-4c5e-b89c-3b65f0bf8c0c)

**Comment by marcelklehr** [comment]
Confirmed again, weird that it worked once for me in debug mode. I've believe, again, that I've fixed it, this time, you'll be the judge of that. Here comes v5.3.3

**Comment by ivanjx** [comment]
just updated now and it’s working fine. thanks.
