### ISSUE TITLE
Tab Sync fails if pipe character "|" exists in page title

### ISSUE THREAD

**Issue by shirocko** [floccusaddon/floccus#1813]
### Which version of floccus are you using?

5.4.0

### How many bookmarks do you have, roughly?

1500

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Chrome 131.0.6778.205

### Which version of Nextcloud Bookmarks are you using? (if relevant)

15.0.4

### Which version of Nextcloud? (if relevant)

30.0.4

### Describe the Bug

If I try so sync my open tabs with Nextcloud via floccus and one tab is the startpage of [t-online.de](https://www.t-online.de/), then one of the following errors occur.
When I navigate to a subpage of t-online.de then the sync is working.
It seems that maybe the "|" in the page title of the startpage is causing that problem.
![image](https://github.com/user-attachments/assets/bdbb68c7-62e0-454a-a680-8595405b94b6)

![image](https://github.com/user-attachments/assets/bfd04221-acc6-4c76-8913-8ca652266ca1)

It seems that the first message E035 is displayed because the sync doesn't work for a long time.
The seccond error E019 occurs directly after I had once a working sync and then navigate back to the startpage and the sync fails again.

The only error I see in the Nextcloud Docker Log Output is:

> bookmarksync [04/Jan/2025:21:01:25 +0000] "PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/3785 HTTP/1.1" 500 1934 

### Expected Behavior

The tabs should synchronize independent of characters in the page title.

### To Reproduce

Open one or more browser tabs and one is the startpage of t-online.de, then the errors will occur.

### Debug log provided

- [ ] I have provided a debug log file

Similar error: #1800

**Comment by marcelklehr** [comment]
Hello @shirocko 

> The only error I see in the Nextcloud Docker Log Output is:
>    bookmarksync [04/Jan/2025:21:01:25 +0000] "PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/3785 HTTP/1.1" 500 1934

This seems to be from the Apache log; nextcloud has a separate log file, though, which logs the full error message that caused the 500 response. This would be vital to obtain.

**Comment by marcelklehr** [comment]
Additionally, it would be interesting which version of Nextcloud Bookmarks you are running on your server.

**Comment by shirocko** [comment]
Sadly there is no entry written in the nextcloud.log when the error occurs.
As I said I am using Nextcloud as a docker container and there the nextcloud log is written to /var/www/html/data/nextcloud.log
There are some errors inside regarding REDIS, but not regarding the Error 500.
I tried it several times and the log does not write any new entries.

**Comment by marcelklehr** [comment]
Ah, then I think I know what the problem is.

**Comment by marcelklehr** [comment]
Should be fixed with the upcoming release

**Comment by shirocko** [comment]
Thanks for the quick reply and new release.
I just installed it in chrome, but the error itself still exists. Only the error message in floccus is a bit different:

E035: Failed to create the following bookmark on the server: - #3802;938[News & E-Mail bei t-online | Politik, Sport, Unterhaltung & Ratgeber](https://www.t-online.de/) parentId: 938 | Zuletzt synchronisiert: vor 4 Minuten

![image](https://github.com/user-attachments/assets/2be67ddd-bb03-4875-abf2-ab0d4616afaf)

**Comment by marcelklehr** [comment]
Mmh, in that case the other explanation for this error is that you have multiple bookmarks for the same URL in the database. Are you comfortable with diving into the SQL console of your Nextcloud database? Then you could check the oc_bookmarks table for duplicate entries with the same url with the following query:

```sql
SELECT url, COUNT(*) AS duplicate_count FROM oc_bookmarks GROUP BY url HAVING COUNT(*) > 1;
```

**Comment by shirocko** [comment]
Well...:D
Summarized the output is the following:

26 urls that exist 2 times
5 urls that exist 3 times
AND
one url, t-online.de, that exist **23** times 

What is curious is that if I search the url within the browser or within Nextcloud Bookmarks plugin I don't find it a single time only as the start page without sub urls.

**Comment by marcelklehr** [comment]
> one url, t-online.de, that exist 23 times

That's curious.


Can you try the following query, which will count the number of duplicates per user?
```
SELECT url, COUNT(*) AS duplicate_count, user_id FROM oc_bookmarks GROUP BY url, user_id HAVING COUNT(*) > 1;
```

**Comment by marcelklehr** [comment]
> What is curious is that if I search the url within the browser or within Nextcloud Bookmarks plugin I don't find it a single time only as the start page without sub urls.

Yeah, that makes sense, because the bookmarks app cannot handle duplicate URLs in any way, so I guess they will just disappear.

**Comment by shirocko** [comment]
Okay I chose the radical path.
I delete all floccus configs, delete all bookmarks entries in Nextcloud and also reinstalled the bookmarks plugin in Nextcloud and also floccus in the browser.
There 23 entries were 10 old entries in the recycle bin, 10 somewhere hidden in the bookmark sync user profile and 3 in the admin server profile of nextcloud.
After i delete everything and configured freshly the sync is working again, also for the tabs and the domain t-online.de

So I guess the duplicated entry maybe have been created during several sync conflict in the past and instead of deleting the old entries, the system added the same bookmarks again und let them be as zombies in the database.

For now the error is fixed for me, but I will see how stable the tab sync is in the future with 2 laptops using the nextcloud instance to exchange there open tabs.

Thank you for your quick response and help.

**Comment by marcelklehr** [comment]
Yep, removal from the database would have been my next suggestion as well. If you hit new problems don't hesitate to open an issue here :)
