### ISSUE TITLE
Cloudflare DDoS protection doesn't let floccus through: New bookmark has name "Just a moment..."

### ISSUE THREAD

**Issue by eku** [floccusaddon/floccus#2068]
### Which version of floccus are you using?

5.7.0

### How many bookmarks do you have, roughly?

200

### Are you using other means to sync bookmarks in parallel to floccus?

No

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Fennec 140

### Describe the Bug

When sharing an URL from Fennect to Floccus the name of the bookmark is always "Just a moment...". URL is correct.

### Expected Behavior

Name of site/url is taken over from the intend sent by the browser.

This worked in the past, but is currently broken.

### To Reproduce

Share a URL from within the browser to floccus.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment]
Hey @eku 
Thank you for taking the time to give feedback by opening this issue! I can not reproduce this with Fennec 143.0.2. It's very likely an issue in fenec and may have been fixed in recent versions. Can you try updating fennec?

**Comment by eku** [comment]
Hi @marcelklehr 
the bug is back again with 5.8.1 of this app.

**Comment by marcelklehr** [comment]
Hi @eku 
Thank you for the heads up. What fixed this issue last time? Is your Fennec up to date?

**Comment by eku** [comment]
Hi Marcel,
if it worked with the installed version of Fennec and I only updated floccus, then I wouldn't suspect Fennec as the cause. What do you think?

**Comment by marcelklehr** [comment]
mh, so last time it didn't work, then you updated floccus, then it worked again, now you updated floccus again and it doesn't work again? The thing is, I never changed anything in this functionality, neither then nor now, I believe.

**Comment by eku** [comment]
I suspect that this concerns bookmarks for pages behind Cloudflare. The message seems very suspicious to me. Does Floccus check the link itself, or could it be that Fennec calls up the link again as part of the “Share link” action in order to refresh the page title?

Do you know of a way to log the contents of Fennec's intent to Floccus? I would like to find out whether Fennec already sends the “Just a moment” message.

**Comment by marcelklehr** [comment]
Floccus checks the link on its own if the browser doesn't send a title. Debug logs are only enabled for dev builds. Maybe there's another App that can display the sent intent?

**Comment by eku** [comment]
> Floccus checks the link on its own if the browser doesn't send a title. 

Looks like Fennec sends the URL only

https://hg-edge.mozilla.org/mozilla-central/file/tip/mobile/android/android-components/components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuCandidate.kt#l497

and Floccus does a request for the title in a form that causes Cloudflare to check the browser. That's not nice.

I'm not sure if [this post](https://community.cloudflare.com/t/verifying-you-are-human-this-may-take-a-few-seconds-couldnt-remove-it-in-any-way/718905/2) gives any hint to what should be changed in Floccus.

**Comment by marcelklehr** [comment]
> Floccus does a request for the title in a form that causes Cloudflare to check the browser

I think these cloudflares checks always happen the first time you visit a site that is protected by cloudflare. There is no way around it. If the website send this page instead of the actual page, there is nothing floccus can do to figure out the correct title. Cloudflare is doing exactly what it advertises, it checks whether the thing on the other end is a human. Floccus will likely always have a hard time to tick that box, unfortunately. 😅

**Comment by eku** [comment]
Would using Android's webview a possible solution to the problem?

```
        webView.settings.javaScriptEnabled = true // Enable JavaScript

        webView.webViewClient = object : WebViewClient() {
            override fun onPageFinished(view: WebView?, url: String?) {
                super.onPageFinished(view, url)
                // Extract the page title after the page finishes loading
                view?.evaluateJavascript("document.title") { title ->
                    Log.d("PageTitle", "Title: $title")
                    // Use the title as needed
                }
            }
        }

        // Load the target URL
        webView.loadUrl("https://example.com")
```

**Comment by marcelklehr** [comment]
The issue is not the user agent, but the captcha. We can load the website, perhaps, but you would still have to manually check the box, so the website has to be in the foreground and we have to somehow wait until the real page is displayed to get the real page title. This is not a good approach.
