### ISSUE TITLE
Login with Google broken with latest kiwi

### ISSUE THREAD

**Issue by Dodgexander** [floccusaddon/floccus#921]
With the latest chromium update to kiwi you can no longer login to Google drive.

### To Reproduce

1. Go to add a Google drive account
2. Click on login with Google
3. Nothing happens

Kiwi: 93.0.4577.11

**Comment by marcelklehr** [comment]
If the kiwi update caused this, this is an issue for the Kiwi devs :/

**Comment by kiwibrowser** [comment]
I'll check @marcelklehr . Arnaud.

**Comment by Manu99it** [comment]
I've used the export/import feature to bypass this, however it seems I can't get it to sync the root folder between edge and kiwi. A specific folder works without problems

**Comment by Dodgexander** [comment]
> I've used the export/import feature to bypass this, however it seems I can't get it to sync the root folder between edge and kiwi. A specific folder works without problems

Other sync extensions also seem to have the same problem. In chrome additional folders can be synced (example; Bookmarks Toolbar. In Kiwi only mobile bookmarks exist, and no root folders can be manually created.

**Comment by kiwibrowser** [comment]
> I'll check @marcelklehr . Arnaud.

Investigation done. Kiwi requires fixes in:
+++ b/chrome/browser/ui/apps/chrome_app_window_client.cc
+++ a/content/browser/renderer_host/navigation_request.cc
+++ b/extensions/browser/api/app_window/app_window_api.cc
+++ b/extensions/browser/app_window/app_window.cc

Floccus uses a little bit unusual way to open the login window but there is nothing wrong with that (it's correct behaviour from them).
A fix will be issued on Kiwi's side and I'll update on this thread once done.

**Comment by gcphym** [comment]
> > I'll check @marcelklehr . Arnaud.
> 
> Investigation done. Kiwi requires fixes in:
> +++ b/chrome/browser/ui/apps/chrome_app_window_client.cc
> +++ a/content/browser/renderer_host/navigation_request.cc
> +++ b/extensions/browser/api/app_window/app_window_api.cc
> +++ b/extensions/browser/app_window/app_window.cc
> 
> Floccus uses a little bit unusual way to open the login window but there is nothing wrong with that (it's correct behaviour from them).
> A fix will be issued on Kiwi's side and I'll update on this thread once done.
https://github.com/kiwibrowser/src.next/issues/202#issuecomment-894621701 (Ｔ▽Ｔ)

**Comment by tortino** [comment]
found workaround for floccus login:
https://github.com/brave/brave-browser/issues/4493#issuecomment-909140037

**Comment by kiwibrowser** [comment]
@marcelklehr It's in the plans of Kiwi to fix the issue very soon, it's a bit more difficult than it seems (but it was fixed in the previous version of Kiwi, so I guess it's manageable)

**Comment by bfosqueUC** [comment]
> @marcelklehr It's in the plans of Kiwi to fix the issue very soon, it's a bit more difficult than it seems (but it was fixed in the previous version of Kiwi, so I guess it's manageable)

Any update on this issue? Is a fix still in the works?

**Comment by jontaix** [comment]
> > @marcelklehr It's in the plans of Kiwi to fix the issue very soon, it's a bit more difficult than it seems (but it was fixed in the previous version of Kiwi, so I guess it's manageable)
> 
> Any update on this issue? Is a fix still in the works?

still not working in floccus

**Comment by ryanwwest** [comment]
> found workaround for floccus login: [brave/brave-browser#4493 (comment)](https://github.com/brave/brave-browser/issues/4493#issuecomment-909140037)

@424344 I didn't see a workaround in that issue (perhaps a comment was deleted?). Would you mind elaborating on how to do the workaround on Kiwi if you know?

**Comment by 424344** [comment]
> workaround on Kiwi

the workaround is to login into floccus on a desktop browser (using gdrive option), then export the floccus config, copy the config file to phone, then import the config in floccus. I've tried some month ago and it was working.

**Comment by niikoo** [comment]
> @marcelklehr It's in the plans of Kiwi to fix the issue very soon, it's a bit more difficult than it seems (but it was fixed in the previous version of Kiwi, so I guess it's manageable)

It's not working in `Kiwi Browser 101.0.4951.40`. Are there any updates?

**Comment by Aleksanaa** [comment]
Not working on `111.0.5563.76`

**Comment by d3ward** [comment]
I know it's been a while . On Kiwi v116 this issue has been fixed and you can now login with Google for syncing . Tested on latest Floccus v4.19.1

**Comment by Manu99it** [comment]
@d3ward seems that syncing root folder is still broken though

**Comment by marcelklehr** [comment]
@Manu99it That seems like a different issue, I recommend opening a new ticket for this
