### ISSUE TITLE
High, constant CPU usage in Firefox

### ISSUE THREAD

**Issue by nirvdrum** [floccusaddon/floccus#973]
### Describe the bug

Ever since upgrading from Firefox 91 to 92, I've noticed very high CPU usage of the browser. I ran in troubleshooting mode and the browser ran fine, indicating it was likely a problem with an add-on. I've since then gone through every add-on I have installed and enabled them one by one, isolating the problematic add-on. Floccus appears to be the source of the issue. I did verify disabling the extension reduces CPU consumption (requiring a browser restart, unfortunately). Enabling the add-on immediately jumps the CPU to 100 - 250%.

It may be that the Firefox upgrade was incidental and the issue was actually due to a Floccus upgrade. I have Floccus automatically update, so I don't know what I may have been running previously.

### To Reproduce

The CPU usage climbs immediately after enabling the add-on. I use WebDAV synchronization. The Floccus panel shows that it is constantly trying to synchronize, with a "normal sync" process.

### Expected behavior

I'd expect Floccus to perform synchronization in the background with bursty CPU usage. Instead, it keeps at least one hardware thread fully utilized.

### Desktop
(please complete the following information)
 - OS: Ubuntu 21.04
 - Browser: Firefox
 - Browser: 92.0
 - Floccus version: 4.8.1
 - Floccus sync method: WebDAV

### Server

I use Fastmail as my WebDAV provider. I do not have any insights into what their deployment environment is.

### Debug log
>It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

>Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw

- [] Debug log provided

Unfortunately, I don't see the the link to download the debug log. My lower-right corner is a link to "Secure your Credentials". I've looked for it on the add-on preferences page, but can't see anything there either.

### Additional context

The add-on is unresponsive when clicking the "Cancel Sync" button.

**Comment by fazlerabbi37** [comment]
Can confirm the issue with Firefox 92 with Nextcloud.

**Comment by marcelklehr** [comment]
Floccus may be caught in an infinite loop :/ Does it help to disable the addon and re-enable it?  Triggering a sync from scratch in the settings (with backup beforehand)?

**Comment by nirvdrum** [comment]
Disabling and re-enabling doesn't help. That was how I was able to narrow down the add-on as being the source of the problem, unfortunately. I haven't tried blowing my settings or anything like that. If there's a way for me to help you debug it, please let me know. I don't have experience with web extensions, but I have general development experience, including writing NPAPI plugins.

**Comment by nirvdrum** [comment]
Ahh, good ol' stalebot.

**Comment by marcelklehr** [comment]
Here's how you can debug:

#### Firefox
* Go to `about:debugging`
* Go to `This firefox`
* click on `inspect` button next to floccus entry
* trigger a sync by clicking on `sync now` for the account of your choice.
* go back to the inspector window and inspect the logs

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* trigger a sync by clicking on `sync now` for the account of your choice
* go back to the inspector window and inspect the logs

**Comment by fazlerabbi37** [comment]
```

**Comment by didierm** [comment]
Issue confirmed with Firefox 94.0.2 (Fedora 35) , floccus 4.8.4 and Nextcloud WewbDAV .xbel storage.

**Comment by didierm** [comment]
* When debugging, I get the same warnings/errors as https://github.com/floccusaddon/floccus/issues/973#issuecomment-962295342 ;
* "Synchronization in progress." message stays forever ;
* When clicking [ Cancel Sync], this error is emitted : 
```
11:01:27.171 Syncing failed with E027: Sync process was interrupted background-script.js:2:230274
    sync moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    s moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    s moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    i moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    (Async: promise callback)
    u moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    s moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    (Async: promise callback)
    u moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    i moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    (Async: promise callback)
    u moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    i moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    (Async: promise callback)
    u moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    s moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    s moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    sync moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    syncAccount moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    scheduleSync moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    add moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    _tryToStartAnother moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    add moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    add moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    scheduleSync moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    checkSync moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    setEnabled moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    (Async: setTimeout handler)
    setEnabled moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    <anonymous> moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    (Async: promise callback)
    <anonymous> moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    <anonymous> moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    <anonymous> moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    <anonymous> moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2

```
```
11:01:27.174 Uncaught (in promise) TypeError: this.syncProcess is undefined
    cancelSync moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    s moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    s moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    s moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    s moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    cancelSync moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    cancelSync moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/background-script.js:2
    CANCEL_SYNC moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    h moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    dispatch moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    dispatch moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    onCancelSync moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    Ut moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    e moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    Ut moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    $emit moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    click moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    Ut moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    e moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    _wrapper moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    bn moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    oi moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    _n moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    h moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    m moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    ca moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    _update moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    n moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    get moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    ge moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    mount moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    $mount moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    init moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    m moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    m moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    g moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    m moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    g moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    m moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    g moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    m moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    g moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    m moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    g moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    m moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    g moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    m moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    ca moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    _update moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
    n moz-extension://2c2bbf32-149c-49a3-8ef1-1f745c224783/dist/js/options.js:2
background-script.js:2:231019
```

**Comment by didierm** [comment]
Some more information :  

* In the above described cases, the commonly observed behaviour is : 
  * a constant high CPU usage as soon as the browser is started ;
  * CPU usage does not drop when disabling the extension ;
  * CPU usage returns to normal when the browser is restarted (with the extension disabled) ;
  * reenabling the extension repeats this pattern.

* For testing purposes, I : 
  * exported the floccus account (NextCloud WebDAV sync) and the (approx. 3000) bookmarks ;
  * imported both the bookmarks and the flocus account in a new Firefox (v94) profile.

With the new Firefox profile, the behaviour is slightly different : 
* CPU usage is normal, until : 
* the floccus icon ("Open Floccus options") is clicked, revealing the sync process.
  * At this point, CPU usage jumps to 100% 
* Hiding the sync process (by e.g. clicking outside the floccus sync popup window) drops CPU usage to normal levels.

**Comment by marcelklehr** [comment]
> * the floccus icon ("Open Floccus options") is clicked, revealing the sync process.
>   * At this point, CPU usage jumps to 100%
> * Hiding the sync process (by e.g. clicking outside the floccus sync popup window) drops CPU usage to normal levels.

Investigating this, I found that the indeterminate loading bar animation at the top of a syncing account card causes a huge CPU load.

> After a successful sync ( [Auto-sync] disabled, [Pull Sync once] button 
> CPU usage is 100% ;

I couldn't reproduce this, so far, but will investigate further.

**Comment by didierm** [comment]
Perhaps providing a test version without the loading bar animation (and the sync animation ?) may shed some proverbial light whether there is a correlation with the other above reported CPU usage issues ?

**Comment by marcelklehr** [comment]
> After a successful sync

How do you know that the sync is successful or even done, if the UI still says loading?

**Comment by didierm** [comment]
> 



> How do you know that the sync is successful or even done, if the UI still says loading?

By examing the Apache/httpd (Nextcloud) access logs : 
```
"GET /pub/remote.php/webdav/{obfuscated}/bookmarks.xbel.lock HTTP/1.1" 404 11415
"PUT /pub/remote.php/webdav/{obfuscated}/bookmarks.xbel.lock HTTP/1.1" 201 -
"GET /pub/remote.php/webdav/{obfuscated}/bookmarks.xbel HTTP/1.1" 200 6982662
```

**Comment by marcelklehr** [comment]
> "GET /pub/remote.php/webdav/{obfuscated}/bookmarks.xbel

This only means that the current server state was fetched, not that sync is finished.

**Comment by didierm** [comment]
Indeed, it seems the sync process does not finish (lockfile is not removed) : 
_(lockfile creation/removal is verified by examining the filesystem directory of the floccus NextCloud/WebDAV folder location)_
```
# ll
total 6824
-rw-r--r-- 1 apache apache 6982662 Nov 23 00:05 bookmarks.xbel
-rw-r--r-- 1 apache apache      42 Nov 24 13:41 bookmarks.xbel.lock
```

* Start browser
* open Floccus

* click **[pull sync once]**
```
[24/Nov/2021:13:47:24 +0100] "GET /pub/remote.php/webdav/{obfuscated}/bookmarks.xbel.lock HTTP/1.1" 200 42
...
[24/Nov/2021:13:47:38 +0100] "GET /pub/remote.php/webdav/{obfuscated}/bookmarks.xbel.lock HTTP/1.1" 200 42
[24/Nov/2021:13:47:42 +0100] "GET /pub/remote.php/webdav/{obfuscated}/bookmarks.xbel.lock HTTP/1.1" 200 42
```

* click **[cancel sync]**
```
[24/Nov/2021:13:47:46 +0100] "DELETE /pub/remote.php/webdav/{obfuscated}/bookmarks.xbel.lock HTTP/1.1" 204 -
```
```
# ll
total 6820
-rw-r--r-- 1 apache apache 6982662 Nov 23 00:05 bookmarks.xbel
```

* click **[pull sync once]**
```
192.168.2.200 - didier [24/Nov/2021:13:51:07 +0100] "GET /pub/remote.php/webdav/{obfuscated}/bookmarks.xbel.lock HTTP/1.1" 404 11415
192.168.2.200 - didier [24/Nov/2021:13:51:08 +0100] "PUT /pub/remote.php/webdav/{obfuscated}/bookmarks.xbel.lock HTTP/1.1" 201 -
192.168.2.200 - didier [24/Nov/2021:13:51:08 +0100] "GET /pub/remote.php/webdav/{obfuscated}/bookmarks.xbel HTTP/1.1" 200 6982662
```
```
# ll
total 6824
-rw-r--r-- 1 apache apache 6982662 Nov 23 00:05 bookmarks.xbel
-rw-r--r-- 1 apache apache      42 Nov 24 13:51 bookmarks.xbel.lock
```

**Comment by marcelklehr** [comment]
@didierm In this case, it would be interesting to know what floccus is stuck on, ideally by debugging: https://github.com/floccusaddon/floccus/issues/973#issuecomment-945893817

**Comment by didierm** [comment]
* I cleared all bookmarks in the Firefox test profile ;

* At 14:42 CET (13:42Z) I reinitialized a Floccus .xbel pull sync (approx. 3000 bookmarks) : 
`-rw-r--r-- 1 apache apache      42 Nov 24 14:42 bookmarks.xbel.lock`

* At 16:44 CET, still high CPU usage : 
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                  
 432949 didier    20   0 6684496   2,2g 251920 R 201,7   7,1 166:39.48 GeckoMain      
```

* "432949" is the main process : 
```
$ ps aux | grep 432949
didier    432949  126  6.9 6684492 2278472 pts/11 Rl+ 14:32 167:37 /usr/lib64/firefox/firefox --no-remote -P test-floccus
```

* The debug info reveals constant processing (reordering ?) of the bookmarks : 
```
2021-11-24T14:58:17.281Z (local)ORDERFOLDER { id: 'L4xuH2r4o2b_',
  order: 
   [ { type: 'bookmark', id: 'v2btO0An_hUZ' },
     { type: 'bookmark', id: 'teSyJO86m1L6' },
     { type: 'bookmark', id: '8k2hhVJvr26A' },
     { type: 'bookmark', id: 'hrAooY0u7S_P' },
     { type: 'bookmark', id: 'DU3pyBxkFwHE' },
     { type: 'bookmark', id: 'A8dkRJnt_fCH' },
     { type: 'bookmark', id: 'IsEi-79XhSzx' },
     { type: 'bookmark', id: '6YqGLfX42DNe' },
     { type: 'bookmark', id: 'LSm9_mDQQKFU' },
     { type: 'bookmark', id: '7XzGxuXWnf7v' },
     { type: 'bookmark', id: 'hDUqI9eSplz1' },
     { type: 'bookmark', id: '8V-QUPed_lDy' },
     { type: 'bookmark', id: 'lG160dAlkgOQ' },
     { type: 'bookmark', id: 'ZKMfLNN4q-d_' },
     { type: 'bookmark', id: 'iaBRy0m1HYgR' },
     { type: 'bookmark', id: '3FLoSH-qoPH7' },
     { type: 'bookmark', id: 'XdBuquQYrKVE' },
     { type: 'bookmark', id: 'B_zZcbDzdaJF' },
     { type: 'bookmark', id: 'XIV94OBpjyjb' },
     { type: 'bookmark', id: 'ETD_CgmYw43N' } ] } background-script.js:2:13335
```
...
```
2021-11-24T14:58:22.885Z { reorderings: 
   [ { type: 'REORDER',
       oldItem: 
        + #8502[Magisk] parentId: 80, hash: undefined
        - #14854[Magisk](https://forum.xda-developers.com/apps/magisk) parentId: 8502
        - #14855[Collection of Magisk Modules v2](https://forum.xda-developers.com/apps/magisk/collection-magisk-modules-v2-t3575758) parentId: 8502
        - #14856[GitHub - Magisk-Modules-Repo/magisk-foldermount: magisk-foldermount](https://github.com/Magisk-Modules-Repo/magisk-foldermount) parentId: 8502
        - #14857[[MODULE] [DEV] Magisk FolderMount v0.8.7.2](https://forum.xda-developers.com/apps/magisk/module-magisk-foldermount-v0-8-t3591215) parentId: 8502
        - #14858[GitHub - Magisk-Modules-Repo/hardware-key-disabler-linage-os: hardware-key-disabler-linage-os](https://github.com/Magisk-Modules-Repo/hardware-key-disabler-linage-os) parentId: 8502
        - #14859[[Module] Hardware Key Disabler for Lineage OS](https://forum.xda-developers.com/apps/magisk/module-hardware-key-disabler-lineage-os-t3579006) parentId: 8502
        - #14860[[Magisk] v9 Module - SD Write Access Enabler v1](https://forum.xda-developers.com/apps/magisk/magisk-v9-module-sd-write-access-t3503988) parentId: 8502
        - #14861[[MODULE] Volume Steps Increase (for Magisk v10+)](https://forum.xda-developers.com/apps/magisk/module-volume-steps-increase-magisk-v10-t3554996) parentId: 8502
        - #14862[[MODULE] Magisk init.d | Universal init.d enabler!](https://forum.xda-developers.com/apps/magisk/module-magisk-init-d-universal-init-d-t3579305) parentId: 8502
        - #14863[[MODULE][TERMINAL EMU] Increase Volume Steps + UI](https://forum.xda-developers.com/apps/magisk/module-increase-volume-steps-ui-t3583040) parentId: 8502
        - #14864[Collection of Magisk Modules v2 - Post #123](https://forum.xda-developers.com/showpost.php?p=72013346&postcount=123) parentId: 8502
        - #14865[[MODULE] [7.x.x] Enable sdcardfs - 7/13/2017](https://forum.xda-developers.com/apps/magisk/module-enable-sdcardfs-t3603375) parentId: 8502
        - #14866[[Magisk][Module] su xbin_bind v1.2-20170417](https://forum.xda-developers.com/apps/magisk/magisk-suxinbind-t3564673) parentId: 8502
        - #14867[Shell Environment enhancements for root - Post #222](https://forum.xda-developers.com/showpost.php?p=72415179&postcount=222) parentId: 8502
        - #14868[[Module] Magic Folder Binder v2017.8.5](https://forum.xda-developers.com/apps/magisk/module-magic-folder-binder-t3621814) parentId: 8502
        - #14869[Magisk-Modules-Repo · GitHub](https://github.com/Magisk-Modules-Repo) parentId: 8502
        - #14870[GitHub - Magisk-Modules-Repo/Greenify4Magisk: Greenify4Magisk](https://github.com/Magisk-Modules-Repo/Greenify4Magisk) parentId: 8502
        - #14871[GitHub - Magisk-Modules-Repo/Unified-Hosts-Adblock: unifiedhostsadblock](https://github.com/Magisk-Modules-Repo/Unified-Hosts-Adblock) parentId: 8502
        - #14872[GitHub - Magisk-Modules-Repo/Busybox-Installer: busybox-ndk](https://github.com/Magisk-Modules-Repo/Busybox-Installer) parentId: 8502
        - #14873[GitHub - Magisk-Modules-Repo/adb-Installer: adb-ndk](https://github.com/Magisk-Modules-Repo/adb-Installer) parentId: 8502,
       payload: 
        + #1JYaOfGf6d7u[Magisk] parentId: 7u-Maw6ApKqa, hash: undefined
        - #14854[Magisk](https://forum.xda-developers.com/apps/magisk) parentId: 8502
        - #14855[Collection of Magisk Modules v2](https://forum.xda-developers.com/apps/magisk/collection-magisk-modules-v2-t3575758) parentId: 8502
        - #14856[GitHub - Magisk-Modules-Repo/magisk-foldermount: magisk-foldermount](https://github.com/Magisk-Modules-Repo/magisk-foldermount) parentId: 8502
        - #14857[[MODULE] [DEV] Magisk FolderMount v0.8.7.2](https://forum.xda-developers.com/apps/magisk/module-magisk-foldermount-v0-8-t3591215) parentId: 8502
        - #14858[GitHub - Magisk-Modules-Repo/hardware-key-disabler-linage-os: hardware-key-disabler-linage-os](https://github.com/Magisk-Modules-Repo/hardware-key-disabler-linage-os) parentId: 8502
        - #14859[[Module] Hardware Key Disabler for Lineage OS](https://forum.xda-developers.com/apps/magisk/module-hardware-key-disabler-lineage-os-t3579006) parentId: 8502
        - #14860[[Magisk] v9 Module - SD Write Access Enabler v1](https://forum.xda-developers.com/apps/magisk/magisk-v9-module-sd-write-access-t3503988) parentId: 8502
        - #14861[[MODULE] Volume Steps Increase (for Magisk v10+)](https://forum.xda-developers.com/apps/magisk/module-volume-steps-increase-magisk-v10-t3554996) parentId: 8502
        - #14862[[MODULE] Magisk init.d | Universal init.d enabler!](https://forum.xda-developers.com/apps/magisk/module-magisk-init-d-universal-init-d-t3579305) parentId: 8502
        - #14863[[MODULE][TERMINAL EMU] Increase Volume Steps + UI](https://forum.xda-developers.com/apps/magisk/module-increase-volume-steps-ui-t3583040) parentId: 8502
        - #14864[Collection of Magisk Modules v2 - Post #123](https://forum.xda-developers.com/showpost.php?p=72013346&postcount=123) parentId: 8502
        - #14865[[MODULE] [7.x.x] Enable sdcardfs - 7/13/2017](https://forum.xda-developers.com/apps/magisk/module-enable-sdcardfs-t3603375) parentId: 8502
        - #14866[[Magisk][Module] su xbin_bind v1.2-20170417](https://forum.xda-developers.com/apps/magisk/magisk-suxinbind-t3564673) parentId: 8502
        - #14867[Shell Environment enhancements for root - Post #222](https://forum.xda-developers.com/showpost.php?p=72415179&postcount=222) parentId: 8502
        - #14868[[Module] Magic Folder Binder v2017.8.5](https://forum.xda-developers.com/apps/magisk/module-magic-folder-binder-t3621814) parentId: 8502
        - #14869[Magisk-Modules-Repo · GitHub](https://github.com/Magisk-Modules-Repo) parentId: 8502
        - #14870[GitHub - Magisk-Modules-Repo/Greenify4Magisk: Greenify4Magisk](https://github.com/Magisk-Modules-Repo/Greenify4Magisk) parentId: 8502
        - #14871[GitHub - Magisk-Modules-Repo/Unified-Hosts-Adblock: unifiedhostsadblock](https://github.com/Magisk-Modules-Repo/Unified-Hosts-Adblock) parentId: 8502
        - #14872[GitHub - Magisk-Modules-Repo/Busybox-Installer: busybox-ndk](https://github.com/Magisk-Modules-Repo/Busybox-Installer) parentId: 8502
        - #14873[GitHub - Magisk-Modules-Repo/adb-Installer: adb-ndk](https://github.com/Magisk-Modules-Repo/adb-Installer) parentId: 8502,
       order: [Object],
       oldOrder: [Object] } ] } background-script.js:2:13335
```

The above debug log is only an extract.

Many bookmarks seem to be constantly reordered, although not at the same rate : 
e.g. in the debug log between 15:05 and 16:52, one bookmark/URL is 442 times present, another bookmark/URL 127 times.

**Comment by didierm** [comment]
Sync completed at 18:21 CET (elapsed time since sync start : 3h 40'), with CPU usage dropping to normal level.
```
2021-11-24T17:21:22.557Z onSyncComplete background-script.js:2:13335
2021-11-24T17:21:29.281Z No changes to the server version necessary background-script.js:2:13335
XHR DELETE   https://{obfuscated}/bookmarks.xbel.lock   [HTTP/1.1 204 No Content 1949ms]
2021-11-24T17:21:33.616Z Successfully ended sync process for account didier@{obfuscated} background-script.js:2:13335
```
```
[Exception... "Failure"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://extensions/content/child/ext-storage.js :: fireOnChanged :: line 179"  data: no] ext-storage.js:179:21
    fireOnChanged chrome://extensions/content/child/ext-storage.js:179
    set chrome://extensions/content/child/ext-storage.js:122
    AsyncFunctionNext self-hosted:692
```
```
Error: An unexpected error occurred background-script.js:2:515532
    syncAccount moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/background-script.js:2
    TRIGGER_SYNC_DOWN moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    h moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    dispatch moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    dispatch moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    onTriggerSyncDown moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    Ut moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    e moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    Ut moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    $emit moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    click moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    Ut moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    e moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    _wrapper moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    (Async: EventListener.handleEvent)
    bn moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    oi moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    _n moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    h moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    m moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    ca moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    _update moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    n moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    get moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    ge moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    mount moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    $mount moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    init moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    m moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    m moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    g moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    m moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    g moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    m moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    g moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    m moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    g moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    m moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    g moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    m moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    ca moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    _update moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    n moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    get moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    ge moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
```
```
Uncaught (in promise) TypeError: can't access dead object
```

* Clicking the **[Pull sync once]** button again, yields high CPU usage again : 
```
No message found with name LabelFunddevelopment in locale en. Using default locale 'en' options.js:2:1292583
No message found with name LabelSecurecredentials in locale en. Using default locale 'en' options.js:2:1292583
No message found with name LabelUnlock in locale en. Using default locale 'en' options.js:2:1292583
No message found with name LabelKey in locale en. Using default locale 'en' options.js:2:1292583
No message found with name LabelUnlock in locale en. Using default locale 'en' options.js:2:1292583
[Vuetify] [UPGRADE] 'v-content' is deprecated, use 'v-main' instead.

found in

---> <VMain>
       <VApp>
         <App> at src/ui/App.vue
           <Root> options.js:2:1565695
Error: Cannot find module './en-US.json'
    r moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    a moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    load moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    promise callback*15420/m</t.prototype.load/</< moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    p moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    p moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    o moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    o moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    load moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    <anonymous> moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    <anonymous> moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
    <anonymous> moz-extension://9f79077e-0a69-4e46-9acd-7642a8979e82/dist/js/options.js:2
options.js:2:1291742
2021-11-24T23:38:15.676Z onSyncStart: begin background-script.js:2:13335
2021-11-24T23:38:15.678Z https://{obfuscated}/bookmarks.xbel.lock background-script.js:2:13335
XHR GET https://{obfuscated}/bookmarks.xbel.lock
[HTTP/1.1 404 Not Found 1484ms]

2021-11-24T23:38:17.232Z https://{obfuscated}/bookmarks.xbel.lock background-script.js:2:13335
XHR PUT https://{obfuscated}/bookmarks.xbel.lock
[HTTP/1.1 201 Created 616ms]

XHR GET https://{obfuscated}/bookmarks.xbel
[HTTP/1.1 200 OK 455ms]

2021-11-24T23:38:25.242Z onSyncStart: completed background-script.js:2:13335
2021-11-24T23:38:25.670Z Using slave strategy background-script.js:2:13335
2021-11-24T23:38:56.537Z Overriding title of built-in node menu________ Bookmarks Menu => Bookmarks Menu background-script.js:2:13335
2021-11-24T23:38:56.538Z Overriding title of built-in node toolbar_____ Bookmarks Toolbar => Bookmarks Bar background-script.js:2:13335
2021-11-24T23:38:56.888Z Overriding title of built-in node unfiled_____ Other Bookmarks => Other Bookmarks background-script.js:2:13335
2021-11-24T23:38:56.888Z Overriding title of built-in node mobile______ Mobile Bookmarks => Mobile Bookmarks background-script.js:2:13335
2021-11-24T23:42:55.286Z { localDiff: [],
  serverDiff: 
   [ { type: 'CREATE',
       payload: 
        + #3788[...
background-script.js:2:13335
2021-11-24T23:42:58.295Z { localTreeRoot: 
     + #root________[undefined] parentId: undefined, hash: 7ca45e88e6c3b9cd8d83c290ab2d13efe6a94f4b0d81c59bf52410311568be42
       + #menu________[Bookmarks Menu] parentId: root________, hash: 8c9613552f39c73f108cb64324940b9f742922a6d531d63cecd6b6b53aed5e0f
   
       + #toolbar_____[Bookmarks Bar] parentId: root________, hash: 97c7858f1a7f50e9af360d15f1e61ba212f8826b66e501a0a713c49bdc53a2af
         + #yFA_RFZDERh8[Privacy] parentId: toolbar_____, hash: c7ed900f5938666d3816b53d9ac0afda326c2de9992e850b5a1ba9b527db0415
           - #JNKlA8v00WwN[...
background-script.js:2:13335
2021-11-24T23:42:59.628Z { revertPlan: [] } background-script.js:2:13335
2021-11-24T23:42:59.631Z Checking failsafe: 0/30886=0 background-script.js:2:13335

...

2021-11-24T23:44:03.803Z (local)CREATEFOLDER     + #7uTZYSakSZij[Redmi Note 7 Pro] parentId: jxaKdzazGBCE, hash: undefined
      - #10406[...
2021-11-24T23:44:03.803Z (local)CREATE     - #uNCtuz4xZIhh[Xiaomi ... parentId: jxaKdzazGBCE background-script.js:2:13335
...

```

**Comment by didierm** [comment]
* After approx. 2 hours (01:46Z) , Floccus sync fails due to depleted storage, i.e. a full disk (`places.sqlite-wal` has grown to approx. 8.5 GB) ;
* Notwithstanding the aborted sync, 
  * Floccus status is still "Synchronization in progress" ;
  * CPU usage is 100%.

**Comment by marcelklehr** [comment]
Woah. Something's going really wrong here :/

**Comment by marcelklehr** [comment]
Can you submit a complete log of this to https://cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw ?

**Comment by didierm** [comment]
Thought so ... Could be the size of my bookmarks collection (?), but there is no info about the bookmarks size of the other reporters.
I could also start dissecting the bookmarks file (by means of HTML export, dissecting, and subsequent import), but not sure whether this effort is worthwhile with cross-reference experience of the other reporters.

**Comment by didierm** [comment]
> Can you submit a complete log of this to https://cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw ?

Sure, I am not opposed to that (no debugging without logs), but : 
1. As the log contains my bookmarks, I would need to vet the entire log for `https://user:password@` occurances, unless there is a regexp for replacing all http(s)://... with e.g. `{url-obfuscated}` ;
2. I do not immediately find a way to export the entire log, only "Export visible messages to file", and as there are tens of thousands of log lines created, older messages are dropped quickly, leaving only a partial (constantly changing) log.

**Comment by didierm** [comment]
> whether this effort is worthwhile with cross-reference experience of the other reporters.
-> ... worthwhile with**OUT** cross-reference experiences ...

**Comment by mnalis** [comment]
@didierm perhaps you can use perl oneliner I wrote in https://github.com/floccusaddon/floccus/issues/912#issuecomment-881459667 to do most of the anonymizing. You would still need to sanity-check that nothing important leaked, but it should do vast majority of the work.

**Comment by fazlerabbi37** [comment]
> @didierm perhaps you can use perl oneliner I wrote in [#912 (comment)](https://github.com/floccusaddon/floccus/issues/912#issuecomment-881459667) to do most of the anonymizing. You would still need to sanity-check that nothing important leaked, but it should do vast majority of the work.

just an idea: would be nice to see in integrated with floccus for sending quick logs.

**Comment by marcelklehr** [comment]
> I found that the indeterminate loading bar animation at the top of a syncing account card causes a huge CPU load.

This should be fixed in the latest release now, at least.

**Comment by didierm** [comment]
>     2. I do not immediately find a way to export the entire log, only "Export visible messages to file", and as there are tens of thousands of log lines created, older messages are dropped quickly, leaving only a partial (constantly changing) log.

Any suggestions for capturing the entire log ?
_(Firefox : menu > Tools > Browser Tools > Web Developer Tools > Console)_

**Comment by fazlerabbi37** [comment]
unfortunately, the problem still persist for me in 4.8.7 :disappointed:

**Comment by didli** [comment]
Issue confirmed for me too. It is especially noticeable with push sync (but happens anyway with the other modes as well).
Worked just fine before firefox 95.0.2 (fedora 35).

**Comment by didierm** [comment]
ping

**Comment by marcelklehr** [comment]
The latest release of floccus now allows always downloading the debug logs from the account settings and also includes anonymized logs.

**Comment by marcelklehr** [comment]
> As the log contains my bookmarks, I would need to vet the entire log for https://user:password@ occurances, unless there is a regexp for replacing all http(s)://... with e.g. {url-obfuscated} ;
> I do not immediately find a way to export the entire log, only "Export visible messages to file", and as there are tens of thousands of log lines created, older messages are dropped quickly, leaving only a partial (constantly changing) log.

@didierm Floccus has log redaction built-in now. Go to settings scroll down to dangerous actions and click on "download anonymized logs"

**Comment by didierm** [comment]
Thank you ; will try again in the near future (bit swamped right now).

**Comment by nolden** [comment]
Hi, I'm observing similar issues with firefox, let me know if I should file it separately. Basically Firefox stops working for me at some point, not responding at all or taking a very long time to load pages. This is what I found out:

Windows task manager shows a very large number of threads for the firefox process, like thousands, but only when floccus is active.
 
On linux I can see this in "top", sync was running, firefox is not responding any more after ~20 minutes

 3751 nolden    20   0   20,3g  16,5g 309560 S   0,0  26,4  22:25.65 firefox                                                                                
 93122 nolden    20   0   20,3g  16,3g  44996 S   0,0  26,0   0:00.00 mozStorage #2                                                                          
 73924 nolden    20   0   27,7g 824308 108008 S   0,0   1,3  45:00.78 WebExtensions


I have around 1700 bookmarks in Nextcloud Bookmarks. 

When I download the anonymized debug log unfortunately it only contains the latest successfull run, I could not see any information from the sync runs that stall forever. If you are interested let me know where I can send it.

**Comment by marcelklehr** [comment]
I may at long last have found a reason for this. Or at least identified one performance hole. Let's see if the next release improves the situation here.

**Comment by cracket** [comment]
I have bad news - upgraded to 4.12.0 and checked if problem still occurs. 
It does. I have run firefox with --safe-mode   - all my mozStorage queries last 1msec. 
I have started ff with all my plugins disabled - same result ( 1-3 msec)

As soon as I enable floccus plugin (4.12.0 with auto-sync turned off) - trace log is getting bombed by huge queries (see log below). 

I'm not running any sync,  floccus debug logs have no new entries. 
As a result 1 core of my CPU is constantly busy due to floccus queries.

( plugin disabled)
2022-03-22 19:57:07.278065 UTC - [Parent 3832: IndexedDB #5]: D/mozStorage TRACE_TIME on 8ce9c9c0: 1ms
2022-03-22 19:57:07.278133 UTC - [Parent 3832: IndexedDB #6]: D/mozStorage TRACE_TIME on 87312840: 1ms
2022-03-22 19:57:27.888246 UTC - [Parent 3832: Main Thread]: D/mozStorage TRACE_TIME on 8c02a060: 1ms
2022-03-22 19:57:27.892388 UTC - [Parent 3832: Main Thread]: D/mozStorage TRACE_TIME on 8c02a060: 2ms
2022-03-22 19:57:27.912102 UTC - [Parent 3832: mozStorage #1]: D/mozStorage TRACE_TIME on 8c02a060: 1ms
2022-03-22 19:57:27.924366 UTC - [Parent 3832: mozStorage #1]: D/mozStorage TRACE_TIME on 8c02a060: 1ms
2022-03-22 19:57:32.603123 UTC - [Parent 3832: Main Thread]: D/mozStorage TRACE_TIME on 8c02a060: 1ms
2022-03-22 19:57:32.606889 UTC - [Parent 3832: Main Thread]: D/mozStorage TRACE_TIME on 8c02a060: 2ms
2022-03-22 19:57:32.626164 UTC - [Parent 3832: mozStorage #1]: D/mozStorage TRACE_TIME on 8c02a060: 1ms
2022-03-22 19:57:32.628137 UTC - [Parent 3832: mozStorage #1]: D/mozStorage TRACE_TIME on 8c02a060: 1ms
2022-03-22 19:57:32.630022 UTC - [Parent 3832: mozStorage #1]: D/mozStorage TRACE_TIME on 8c02a060: 1ms
2022-03-22 19:57:32.633231 UTC - [Parent 3832: mozStorage #1]: D/mozStorage TRACE_TIME on 8c02a060: 1ms
2022-03-22 19:58:32.615224 UTC - [Parent 3832: mozStorage #2]: D/mozStorage TRACE_TIME on 8c02a420: 1ms
2022-03-22 19:58:34.951146 UTC - [Parent 3832: mozStorage #2]: D/mozStorage TRACE_TIME on 8c02a420: 1ms
2022-03-22 19:58:34.954045 UTC - [Parent 3832: mozStorage #1]: D/mozStorage TRACE_TIME on 8c02a060: 1ms
2022-03-22 19:58:34.968110 UTC - [Parent 3832: mozStorage #1]: D/mozStorage TRACE_TIME on 8c02a060: 1ms
2022-03-22 19:58:41.660079 UTC - [Parent 3832: mozStorage #1]: D/mozStorage TRACE_TIME on 8c02a060: 1ms
2022-03-22 19:58:42.478040 UTC - [Parent 3832: mozStorage #4]: D/mozStorage TRACE_TIME on 87312e80: 1ms
2022-03-22 19:58:42.479025 UTC - [Parent 3832: mozStorage #4]: D/mozStorage TRACE_TIME on 87312e80: 1ms

( plugin enabled from firefox UI somewhere here) 

2022-03-22 19:59:26.367696 UTC - [Parent 3832: Permission]: D/mozStorage TRACE_TIME on 9ee1d9c0: 20ms
2022-03-22 19:59:26.377832 UTC - [Parent 3832: Permission]: D/mozStorage TRACE_TIME on 9ee1d9c0: 10ms
2022-03-22 19:59:26.397338 UTC - [Parent 3832: Permission]: D/mozStorage TRACE_TIME on 9ee1d9c0: 19ms
2022-03-22 19:59:26.765038 UTC - [Parent 3832: QuotaManager IO]: D/mozStorage TRACE_TIME on 80606e80: 1ms
2022-03-22 19:59:26.775010 UTC - [Parent 3832: IndexedDB #8]: D/mozStorage TRACE_TIME on 80607240: 1ms
2022-03-22 19:59:26.776056 UTC - [Parent 3832: IndexedDB #8]: D/mozStorage TRACE_TIME on 80607240: 1ms
2022-03-22 19:59:28.036034 UTC - [Parent 3832: mozStorage #4]: D/mozStorage TRACE_TIME on 87312e80: 1ms
2022-03-22 19:59:29.766041 UTC - [Parent 3832: IndexedDB #8]: D/mozStorage TRACE_TIME on 80607240: 1ms
2022-03-22 19:59:33.819101 UTC - [Parent 3832: IndexedDB #8]: D/mozStorage TRACE_TIME on 80607240: 1ms
2022-03-22 19:59:53.309107 UTC - [Parent 3832: QuotaManager IO]: D/mozStorage TRACE_TIME on 7f115ca0: 1ms
2022-03-22 19:59:53.336190 UTC - [Parent 3832: mozStorage #4]: D/mozStorage TRACE_TIME on 87312e80: 1ms
2022-03-22 19:59:53.412294 UTC - [Parent 3832: mozStorage #1]: D/mozStorage TRACE_TIME on 8c02a060: 1ms
2022-03-22 19:59:53.415271 UTC - [Parent 3832: mozStorage #1]: D/mozStorage TRACE_TIME on 8c02a060: 1ms
2022-03-22 19:59:54.507044 UTC - [Parent 3832: mozStorage #1]: D/mozStorage TRACE_TIME on 8c02a060: 1ms
2022-03-22 19:59:54.516112 UTC - [Parent 3832: mozStorage #1]: D/mozStorage TRACE_TIME on 8c02a060: 1ms
2022-03-22 20:00:13.051655 UTC - [Parent 3832: mozStorage #2]: D/mozStorage TRACE_TIME on 8c02a420: **46231**ms
2022-03-22 20:00:13.056107 UTC - [Parent 3832: mozStorage #1]: D/mozStorage TRACE_TIME on 8c02a060: 1ms
2022-03-22 20:00:37.774207 UTC - [Parent 3832: mozStorage #1]: D/mozStorage TRACE_TIME on 8c02a060: 1ms
2022-03-22 20:00:38.129075 UTC - [Parent 3832: QuotaManager IO]: D/mozStorage TRACE_TIME on 7cd6e660: 1ms
2022-03-22 20:00:38.150135 UTC - [Parent 3832: IndexedDB #8]: D/mozStorage TRACE_TIME on 806fc340: 1ms
2022-03-22 20:00:38.256090 UTC - [Parent 3832: mozStorage #1]: D/mozStorage TRACE_TIME on 8c02a060: 1ms
2022-03-22 20:00:38.338324 UTC - [Parent 3832: mozStorage #1]: D/mozStorage TRACE_TIME on 8c02a060: 1ms
2022-03-22 20:00:39.229389 UTC - [Parent 3832: mozStorage #1]: D/mozStorage TRACE_TIME on 8c02a060: 1ms
2022-03-22 20:00:59.525025 UTC - [Parent 3832: mozStorage #2]: D/mozStorage TRACE_TIME on 8c02a420: **46474**ms
2022-03-22 20:01:26.751017 UTC - [Parent 3832: IndexedDB #9]: D/mozStorage TRACE_TIME on 806fdc40: 1ms
2022-03-22 20:01:44.795637 UTC - [Parent 3832: mozStorage #2]: D/mozStorage TRACE_TIME on 8c02a420: **45270**ms
2022-03-22 20:02:02.430044 UTC - [Parent 3832: IndexedDB #9]: D/mozStorage TRACE_TIME on 806fc7a0: 1ms
2022-03-22 20:02:02.433272 UTC - [Parent 3832: IndexedDB #9]: D/mozStorage TRACE_TIME on 806fc7a0: 1ms
2022-03-22 20:02:02.625379 UTC - [Parent 3832: IndexedDB #9]: D/mozStorage TRACE_TIME on 806fc7a0: 1ms
2022-03-22 20:02:26.750027 UTC - [Parent 3832: IndexedDB #9]: D/mozStorage TRACE_TIME on 97cfb1a0: 1ms
2022-03-22 20:02:26.752135 UTC - [Parent 3832: IndexedDB #9]: D/mozStorage TRACE_TIME on 97cfb1a0: 1ms
2022-03-22 20:02:30.359737 UTC - [Parent 3832: mozStorage #2]: D/mozStorage TRACE_TIME on 8c02a420: **45564**ms
2022-03-22 20:03:15.898935 UTC - [Parent 3832: mozStorage #2]: D/mozStorage TRACE_TIME on 8c02a420: **45538**ms
2022-03-22 20:03:26.751017 UTC - [Parent 3832: IndexedDB #10]: D/mozStorage TRACE_TIME on 7f115b60: 1ms
2022-03-22 20:03:26.753045 UTC - [Parent 3832: IndexedDB #10]: D/mozStorage TRACE_TIME on 7f115b60: 1ms
2022-03-22 20:03:28.776026 UTC - [Parent 3832: IndexedDB #10]: D/mozStorage TRACE_TIME on 7f115b60: 1ms
2022-03-22 20:04:01.202003 UTC - [Parent 3832: mozStorage #2]: D/mozStorage TRACE_TIME on 8c02a420: **45302**ms

**Comment by cracket** [comment]
one more remark related to my previous comment - I have cleared my whole browsing history so only bookmarks managed by floccus are kept within profile:
```
-rw-r--r--  1 linux linux 15728640 mar 22 21:07 places.sqlite
-rw-r--r--  1 linux linux 12091392 mar 22 20:53 favicons.sqlite
-rw-r--r--  1 linux linux  5574672 mar 22 21:07 places.sqlite-wal
-rw-r--r--  1 linux linux  4328576 lut 12 19:38 storage-sync-v2.sqlite-wal
-rw-r--r--  1 linux linux  4128768 mar 22 21:07 webappsstore.sqlite
-rw-r--r--  1 linux linux  1016584 mar 22 21:07 favicons.sqlite-wal
-rw-r--r--  1 linux linux   557496 mar 22 21:17 cookies.sqlite-wal
-rw-r--r--  1 linux linux   524288 mar 22 21:17 cookies.sqlite
```

I'm surprised by still huge size of favicons, but I assume it should not impact synchronization queries

**Comment by didierm** [comment]
ping

**Comment by marcelklehr** [comment]
@cracket Thanks for sharing these, should be quite useful in tackling this!

**Comment by marcelklehr** [comment]
Can you try the latest release and see if that fixes things?

**Comment by nirvdrum** [comment]
We should probably keep this open until the issue is confirmed to be fixed.

**Comment by marcelklehr** [comment]
> Can you try the latest release and see if that fixes things?

@nirvdrum I'm happy to collaborate and troubleshoot and work on fixes, but I need feedback. If nobody tests the latest release I'm close the issue.

**Comment by cracket** [comment]
Sorry for delay, but I didnt have access to slow hardware. 

I've checked version 4.13.1 and there are some good news - namely there were only 5 huge queries executed taking 45 secs each. After that - there are no huge queries looping for ever while firefox is idle. I have no proof these queries origin from flooccus and not firefox itself, but I attach some logs for you:

```
2022-05-09 15:33:01.174300 UTC - [Parent 2795: Cookie]: D/mozStorage Opening connection to 'cookies.sqlite' (a3d03700)
2022-05-09 15:33:06.872151 UTC - [Parent 2795: mozStorage #2]: D/mozStorage TRACE_STMT on 90c67740: '/* do not warn (bug no): cannot use an index */
       WITH RECURSIVE
       descendants(fk, level, type, id, guid, parent, parentGuid, position,
                   title, dateAdded, lastModified) AS (
         SELECT b1.fk, 0, b1.type, b1.id, b1.guid, b1.parent,
                (SELECT guid FROM moz_bookmarks WHERE id = b1.parent),
                b1.position, b1.title, b1.dateAdded, b1.lastModified
         FROM moz_bookmarks b1 WHERE b1.guid='root________'
         UNION ALL
         SELECT b2.fk, level + 1, b2.type, b2.id, b2.guid, b2.parent,
                descendants.guid, b2.position, b2.title, b2.dateAdded,
                b2.lastModified
         FROM moz_bookmarks b2
         JOIN descendants ON b2.parent = descendants.id AND b2.id <> 4)
       SELECT d.level, d.id, d.guid, d.parent, d.parentGuid, d.type,
              d.position AS [index], IFNULL(d.title, '') AS title, d.dateAdded,
              d.lastModified, h.url, (SELECT icon_url FROM moz_icons i
                      JOIN moz_icons_to_pages ON icon_id = i.id
                      JOIN moz_pages_w_icons pi ON page_id = pi.id
                      WHERE pi.page_url_hash = hash(h.url) AND pi.page_url = h.url
                      ORDER BY width DESC LIMIT 1) AS iconuri,
              (SELECT GROUP_CONCAT(t.title, ',')
               FROM moz_bookmarks b2
               JOIN moz_bookmarks t ON t.id = +b2.parent AND t.parent = 4
               WHERE b2.fk = h.id
              ) AS tags,
              (SELECT a.conten	t FROM moz_annos a
               JOIN moz_anno_attributes n ON a.anno_attribute_id = n.id
               WHERE place_id = h.id AND n.name = 'URIProperties/characterSet'
              ) AS charset
       FROM descendants d
       LEFT JOIN moz_bookmarks b3 ON b3.id = d.parent
       LEFT JOIN moz_places h ON h.id = d.fk
       ORDER BY d.level, d.parent, d.position'
2022-05-09 15:33:52.436852 UTC - [Parent 2795: mozStorage #2]: D/mozStorage TRACE_TIME on 90c67740: 45564ms

2022-05-09 15:33:52.440815 UTC - [Parent 2795: mozStorage #2]: D/mozStorage TRACE_STMT on 90c67740: '/* do not warn (bug no): cannot use an index */
       WITH RECURSIVE
       descendants(fk, level, type, id, guid, parent, parentGuid, position,
                   title, dateAdded, lastModified) AS (
         SELECT b1.fk, 0, b1.type, b1.id, b1.guid, b1.parent,
                (SELECT guid FROM moz_bookmarks WHERE id = b1.parent),
                b1.position, b1.title, b1.dateAdded, b1.lastModified
         FROM moz_bookmarks b1 WHERE b1.guid='root________'
         UNION ALL
         SELECT b2.fk, level + 1, b2.type, b2.id, b2.guid, b2.parent,
                descendants.guid, b2.position, b2.title, b2.dateAdded,
                b2.lastModified
         FROM moz_bookmarks b2
         JOIN descendants ON b2.parent = descendants.id AND b2.id <> 4)
       SELECT d.level, d.id, d.guid, d.parent, d.parentGuid, d.type,
              d.position AS [index], IFNULL(d.title, '') AS title, d.dateAdded,
              d.lastModified, h.url, (SELECT icon_url FROM moz_icons i
                      JOIN moz_icons_to_pages ON icon_id = i.id
                      JOIN moz_pages_w_icons pi ON page_id = pi.id
                      WHERE pi.page_url_hash = hash(h.url) AND pi.page_url = h.url
                      ORDER BY width DESC LIMIT 1) AS iconuri,
              (SELECT GROUP_CONCAT(t.title, ',')
               FROM moz_bookmarks b2
               JOIN moz_bookmarks t ON t.id = +b2.parent AND t.parent = 4
               WHERE b2.fk = h.id
              ) AS tags,
              (SELECT a.content FROM moz_annos a
               JOIN moz_anno_attributes n ON a.anno_attribute_id = n.id
               WHERE place_id = h.id AND n.name = 'URIProperties/characterSet'
              ) AS charset
       FROM descendants d
       LEFT JOIN moz_bookmarks b3 ON b3.id = d.parent
       LEFT JOIN moz_places h ON h.id = d.fk
       ORDER BY d.level, d.parent, d.position'
2022-05-09 15:34:38.760232 UTC - [Parent 2795: mozStorage #2]: D/mozStorage TRACE_TIME on 90c67740: 46320ms

2022-05-09 15:34:38.760557 UTC - [Parent 2795: mozStorage #2]: D/mozStorage TRACE_STMT on 90c67740: '/* do not warn (bug no): cannot use an index */
       WITH RECURSIVE
       descendants(fk, level, type, id, guid, parent, parentGuid, position,
                   title, dateAdded, lastModified) AS (
         SELECT b1.fk, 0, b1.type, b1.id, b1.guid, b1.parent,
                (SELECT guid FROM moz_bookmarks WHERE id = b1.parent),
                b1.position, b1.title, b1.dateAdded, b1.lastModified
         FROM moz_bookmarks b1 WHERE b1.guid='root________'
         UNION ALL
         SELECT b2.fk, level + 1, b2.type, b2.id, b2.guid, b2.parent,
                descendants.guid, b2.position, b2.title, b2.dateAdded,
                b2.lastModified
         FROM moz_bookmarks b2
         JOIN descendants ON b2.parent = descendants.id AND b2.id <> 4)
       SELECT d.level, d.id, d.guid, d.parent, d.parentGuid, d.type,
              d.position AS [index], IFNULL(d.title, '') AS title, d.dateAdded,
              d.lastModified, h.url, (SELECT icon_url FROM moz_icons i
                      JOIN moz_icons_to_pages ON icon_id = i.id
                      JOIN moz_pages_w_icons pi ON page_id = pi.id
                      WHERE pi.page_url_hash = hash(h.url) AND pi.page_url = h.url
                      ORDER BY width DESC LIMIT 1) AS iconuri,
              (SELECT GROUP_CONCAT(t.title, ',')
               FROM moz_bookmarks b2
               JOIN moz_bookmarks t ON t.id = +b2.parent AND t.parent = 4
               WHERE b2.fk = h.id
              ) AS tags,
              (SELECT a.content FROM moz_annos a
               JOIN moz_anno_attributes n ON a.anno_attribute_id = n.id
               WHERE place_id = h.id AND n.name = 'URIProperties/characterSet'
              ) AS charset
       FROM descendants d
       LEFT JOIN moz_bookmarks b3 ON b3.id = d.parent
       LEFT JOIN moz_places h ON h.id = d.fk
       ORDER BY d.level, d.parent, d.position'
2022-05-09 15:35:24.738786 UTC - [Parent 2795: mozStorage #2]: D/mozStorage TRACE_TIME on 90c67740: 45978ms

2022-05-09 15:35:24.739084 UTC - [Parent 2795: mozStorage #2]: D/mozStorage TRACE_STMT on 90c67740: '/* do not warn (bug no): cannot use an index */
       WITH RECURSIVE
       descendants(fk, level, type, id, guid, parent, parentGuid, position,
                   title, dateAdded, lastModified) AS (
         SELECT b1.fk, 0, b1.type, b1.id, b1.guid, b1.parent,
                (SELECT guid FROM moz_bookmarks WHERE id = b1.parent),
                b1.position, b1.title, b1.dateAdded, b1.lastModified
         FROM moz_bookmarks b1 WHERE b1.guid='root________'
         UNION ALL
         SELECT b2.fk, level + 1, b2.type, b2.id, b2.guid, b2.parent,
                descendants.guid, b2.position, b2.title, b2.dateAdded,
                b2.lastModified
         FROM moz_bookmarks b2
         JOIN descendants ON b2.parent = descendants.id AND b2.id <> 4)
       SELECT d.level, d.id, d.guid, d.parent, d.parentGuid, d.type,
              d.position AS [index], IFNULL(d.title, '') AS title, d.dateAdded,
              d.lastModified, h.url, (SELECT icon_url FROM moz_icons i
                      JOIN moz_icons_to_pages ON icon_id = i.id
                      JOIN moz_pages_w_icons pi ON page_id = pi.id
                      WHERE pi.page_url_hash = hash(h.url) AND pi.page_url = h.url
                      ORDER BY width DESC LIMIT 1) AS iconuri,
              (SELECT GROUP_CONCAT(t.title, ',')
               FROM moz_bookmarks b2
               JOIN moz_bookmarks t ON t.id = +b2.parent AND t.parent = 4
               WHERE b2.fk = h.id
              ) AS tags,
              (SELECT a.content FROM moz_annos a
               JOIN moz_anno_attributes n ON a.anno_attribute_id = n.id
               WHERE place_id = h.id AND n.name = 'URIProperties/characterSet'
              ) AS charset
       FROM descendants d
       LEFT JOIN moz_bookmarks b3 ON b3.id = d.parent
       LEFT JOIN moz_places h ON h.id = d.fk
       ORDER BY d.level, d.parent, d.position'
2022-05-09 15:36:10.968393 UTC - [Parent 2795: mozStorage #2]: D/mozStorage TRACE_TIME on 90c67740: 46229ms



2022-05-09 15:36:10.968703 UTC - [Parent 2795: mozStorage #2]: D/mozStorage TRACE_STMT on 90c67740: '/* do not warn (bug no): cannot use an index */
       WITH RECURSIVE
       descendants(fk, level, type, id, guid, parent, parentGuid, position,
                   title, dateAdded, lastModified) AS (
         SELECT b1.fk, 0, b1.type, b1.id, b1.guid, b1.parent,
                (SELECT guid FROM moz_bookmarks WHERE id = b1.parent),
                b1.position, b1.title, b1.dateAdded, b1.lastModified
         FROM moz_bookmarks b1 WHERE b1.guid='root________'
         UNION ALL
         SELECT b2.fk, level + 1, b2.type, b2.id, b2.guid, b2.parent,
                descendants.guid, b2.position, b2.title, b2.dateAdded,
                b2.lastModified
         FROM moz_bookmarks b2
         JOIN descendants ON b2.parent = descendants.id AND b2.id <> 4)
       SELECT d.level, d.id, d.guid, d.parent, d.parentGuid, d.type,
              d.position AS [index], IFNULL(d.title, '') AS title, d.dateAdded,
              d.lastModified, h.url, (SELECT icon_url FROM moz_icons i
                      JOIN moz_icons_to_pages ON icon_id = i.id
                      JOIN moz_pages_w_icons pi ON page_id = pi.id
                      WHERE pi.page_url_hash = hash(h.url) AND pi.page_url = h.url
                      ORDER BY width DESC LIMIT 1) AS iconuri,
              (SELECT GROUP_CONCAT(t.title, ',')
               FROM moz_bookmarks b2
               JOIN moz_bookmarks t ON t.id = +b2.parent AND t.parent = 4
               WHERE b2.fk = h.id
              ) AS tags,
              (SELECT a.content FROM moz_annos a
               JOIN moz_anno_attributes n ON a.anno_attribute_id = n.id
               WHERE place_id = h.id AND n.name = 'URIProperties/characterSet'
              ) AS charset
       FROM descendants d
       LEFT JOIN moz_bookmarks b3 ON b3.id = d.parent
       LEFT JOIN moz_places h ON h.id = d.fk
       ORDER BY d.level, d.parent, d.position'
2022-05-09 15:36:57.471020 UTC - [Parent 2795: mozStorage #2]: D/mozStorage TRACE_TIME on 90c67740: 46502ms

```

**Comment by marcelklehr** [comment]
Nice, I have indeed added a cache for the bookmarks full tree query which should result in a fixed number of long running queries on startup and no long running queries during runtime of the browser as you report. This means we've finally found the performance sink! If there was a different way to find out the id of the root folder I'd use it, but as of yet, to my knowledge, there is not.
